const newsData = [
  {
    title: {
      en: "Learn medical terminology, abbreviations, and medications easily",
      uk: "Зручно вивчайте медичні терміни, скорочення та медикаменти",
      ru: "Удобно изучайте медицинские термины, сокращения и медикаменты",
      de: "Medizinische Begriffe, Abkürzungen und Medikamente einfach lernen",
      tr: "Tıbbi terimleri, kısaltmaları ve ilaçları kolayca öğrenin",
      ar: "تعلم المصطلحات الطبية، والاختصارات، والأدوية بسهولة",
      fr: "Apprenez facilement les termes médicaux, abréviations et médicaments",
      es: "Aprende términos médicos, abreviaturas y medicamentos fácilmente",
      pl: "Łatwe poznawanie terminów medycznych, skrótów i leków",
      el: "Μάθετε εύκολα ιατρικούς όρους, συντομογραφίες και φάρμακα",
      ro: "Învățați ușor terminologia medicală, abrevierile și medicamentele"
    },
    summary: {
      en: "On our platform, you can conveniently study and practice medical terms, abbreviations, and medications. Check it out here!",
      uk: "На нашій платформі ви можете зручно вивчати та практикувати медичні терміни, скорочення та медикаменти. Перевірте це тут!",
      ru: "На нашей платформе вы можете удобно изучать и практиковать медицинские термины, сокращения и медикаменты. Ознакомьтесь здесь!",
      de: "Auf unserer Plattform können Sie bequem medizinische Begriffe, Abkürzungen und Medikamente lernen und üben. Schauen Sie hier!",
      tr: "Platformumuzda tıbbi terimleri, kısaltmaları ve ilaçları rahatça öğrenebilir ve alıştırma yapabilirsiniz. Buraya göz atın!",
      ar: "على منصتنا، يمكنك بسهولة دراسة وممارسة المصطلحات الطبية، والاختصارات، والأدوية. اطلع عليها هنا!",
      fr: "Sur notre plateforme, vous pouvez facilement apprendre et pratiquer les termes médicaux, abréviations et médicaments. Vérifiez-le ici!",
      es: "En nuestra plataforma, puedes aprender y practicar términos médicos, abreviaturas y medicamentos fácilmente. ¡Míralo aquí!",
      pl: "Na naszej platformie możesz wygodnie uczyć się i ćwiczyć terminy medyczne, skróty i leki. Sprawdź to tutaj!",
      el: "Στην πλατφόρμα μας μπορείτε εύκολα να μάθετε και να εξασκηθείτε σε ιατρικούς όρους, συντομογραφίες και φάρμακα. Δείτε το εδώ!",
      ro: "Pe platforma noastră puteți învăța și exersa termenii medicali, abrevierile și medicamentele în mod convenabil. Verificați aici!"
    },
    fullText: {
      en: "You can conveniently explore and master medical terminology, abbreviations, and medications directly on our platform. Visit: <a href='/terminology-learning'>Terminology Learning</a>, <a href='/abbreviations-learning'>Abbreviation Learning</a>, <a href='/medications-learning'>Medications Learning</a>",
      uk: "Ви можете зручно досліджувати та вивчати медичну термінологію, скорочення та медикаменти безпосередньо на нашій платформі. Перейдіть сюди: <a href='/terminology-learning'>Вивчення термінології</a>, <a href='/abbreviations-learning'>Вивчення скорочень</a>, <a href='/medications-learning'>Вивчення медикаментів</a>",
      ru: "Вы можете удобно изучать и осваивать медицинскую терминологию, сокращения и медикаменты прямо на нашей платформе. Перейдите сюда: <a href='/terminology-learning'>Изучение терминологии</a>, <a href='/abbreviations-learning'>Изучение сокращений</a>, <a href='/medications-learning'>Изучение медикаментов</a>",
      de: "Sie können bequem medizinische Begriffe, Abkürzungen und Medikamente direkt auf unserer Plattform erkunden und beherrschen. Besuchen Sie: <a href='/terminology-learning'>Terminologie Lernen</a>, <a href='/abbreviations-learning'>Abkürzungen Lernen</a>, <a href='/medications-learning'>Medikamenten Lernen</a>",
      tr: "Platformumuzda doğrudan tıbbi terimleri, kısaltmaları ve ilaçları keşfedebilir ve ustalaşabilirsiniz. Burayı ziyaret edin: <a href='/terminology-learning'>Terminoloji Öğrenimi</a>, <a href='/abbreviations-learning'>Kısaltma Öğrenimi</a>, <a href='/medications-learning'>İlaç Öğrenimi</a>",
      ar: "يمكنك بسهولة استكشاف وإتقان المصطلحات الطبية، والاختصارات، والأدوية مباشرةً على منصتنا. قم بزيارة: <a href='/terminology-learning'>تعلم المصطلحات</a>, <a href='/abbreviations-learning'>تعلم الاختصارات</a>, <a href='/medications-learning'>تعلم الأدوية</a>",
      fr: "Vous pouvez facilement explorer et maîtriser la terminologie médicale, les abréviations et les médicaments directement sur notre plateforme. Visitez: <a href='/terminology-learning'>Apprentissage de la terminologie</a>, <a href='/abbreviations-learning'>Apprentissage des abréviations</a>, <a href='/medications-learning'>Apprentissage des médicaments</a>",
      es: "Puedes explorar y dominar cómodamente la terminología médica, abreviaturas y medicamentos directamente en nuestra plataforma. Visita: <a href='/terminology-learning'>Aprendizaje de terminología</a>, <a href='/abbreviations-learning'>Aprendizaje de abreviaturas</a>, <a href='/medications-learning'>Aprendizaje de medicamentos</a>",
      pl: "Możesz wygodnie zapoznać się z terminologią medyczną, skrótami i lekami bezpośrednio na naszej platformie. Odwiedź: <a href='/terminology-learning'>Nauka terminologii</a>, <a href='/abbreviations-learning'>Nauka skrótów</a>, <a href='/medications-learning'>Nauka leków</a>",
      el: "Μπορείτε εύκολα να εξερευνήσετε και να κατακτήσετε την ιατρική ορολογία, τις συντομογραφίες και τα φάρμακα απευθείας στην πλατφόρμα μας. Επισκεφθείτε: <a href='/terminology-learning'>Εκμάθηση ορολογίας</a>, <a href='/abbreviations-learning'>Εκμάθηση συντομογραφιών</a>, <a href='/medications-learning'>Εκμάθηση φαρμάκων</a>",
      ro: "Puteți explora și stăpâni convenabil terminologia medicală, abrevierile și medicamentele direct pe platforma noastră. Vizitați: <a href='/terminology-learning'>Învățare terminologie</a>, <a href='/abbreviations-learning'>Învățare abrevieri</a>, <a href='/medications-learning'>Învățare medicamente</a>"
    },
    date: "31.05.2025",
  },
  {
    title: {
      en: "First platform launch!",
      uk: "Перший запуск платформи!",
      ru: "Первый запуск платформы!",
      de: "Erster Start der Plattform!",
      tr: "Platformun ilk lansmanı!",
      ar: "إطلاق المنصة لأول مرة!",
      fr: "Premier lancement de la plateforme!",
      es: "¡Primer lanzamiento de la plataforma!",
      pl: "Pierwsze uruchomienie platformy!",
      el: "Πρώτη εκκίνηση της πλατφόρμας!",
      ro: "Prima lansare a platformei!"
    },
    summary: {
      en: "We are excited to announce the launch of our new platform.",
      uk: "Ми раді повідомити про запуск нашої нової платформи.",
      ru: "Мы рады объявить о запуске нашей новой платформы.",
      de: "Wir freuen uns, den Start unserer neuen Plattform bekannt zu geben.",
      tr: "Yeni platformumuzun lansmanını duyurmaktan heyecan duyuyoruz.",
      ar: "نحن متحمسون للإعلان عن إطلاق منصتنا الجديدة.",
      fr: "Nous sommes ravis d'annoncer le lancement de notre nouvelle plateforme.",
      es: "Estamos emocionados de anunciar el lanzamiento de nuestra nueva plataforma.",
      pl: "Jesteśmy podekscytowani, mogąc ogłosić uruchomienie naszej nowej platformy.",
      el: "Είμαστε ενθουσιασμένοι να ανακοινώσουμε την έναρξη της νέας μας πλατφόρμας.",
      ro: "Suntem încântați să anunțăm lansarea noii noastre platforme."
    },
    fullText: {
      en: "Detailed information about the launch of our platform in English. Additional details: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. Sed sit amet ipsum mauris.",
      uk: "Детальна інформація про запуск нашої платформи українською. Додаткові деталі: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. Sed sit amet ipsum mauris.",
      ru: "Подробная информация о запуске нашей платформы на русском. Дополнительные детали: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. Sed sit amet ipsum mauris.",
      de: "Ausführliche Informationen zum Start unserer Plattform auf Deutsch. Zusätzliche Details: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. Sed sit amet ipsum mauris.",
      tr: "Platformumuzun lansmanı hakkında detaylı bilgiler Türkçe. Ek bilgiler: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. Sed sit amet ipsum mauris.",
      ar: "معلومات مفصلة حول إطلاق منصتنا باللغة العربية. تفاصيل إضافية: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. Sed sit amet ipsum mauris.",
      fr: "Informations détaillées sur le lancement de notre plateforme en français. Détails supplémentaires: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. Sed sit amet ipsum mauris.",
      es: "Información detallada sobre el lanzamiento de nuestra plataforma en español. Detalles adicionales: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. Sed sit amet ipsum mauris.",
      pl: "Szczegółowe informacje o uruchomieniu naszej platformy po polsku. Dodatkowe szczegóły: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. Sed sit amet ipsum mauris.",
      el: "Λεπτομερείς πληροφορίες για την εκκίνηση της πλατφόρμας μας στα Ελληνικά. Πρόσθετες λεπτομέρειες: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. Sed sit amet ipsum mauris.",
      ro: "Informații detaliate despre lansarea platformei noastre în română. Detalii suplimentare: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. Sed sit amet ipsum mauris."
    },
    date: "27.03.2025",
  },
  {
    title: {
      en: "New Regional Updates",
      uk: "Нові оновлення для регіонів",
      ru: "Новые обновления по регионам",
      de: "Neue regionale Updates",
      tr: "Bölgesel güncellemeler",
      ar: "تحديثات إقليمية جديدة",
      fr: "Nouvelles mises à jour régionales",
      es: "Nuevas actualizaciones regionales",
      pl: "Nowe aktualizacje regionalne",
      el: "Νέες περιφερειακές ενημερώσεις",
      ro: "Actualizări regionale noi"
    },
    summary: {
      en: "We have added more detailed information for each region.",
      uk: "Ми додали більше детальної інформації для кожного регіону.",
      ru: "Мы добавили более подробную информацию для каждого региона.",
      de: "Wir haben detailliertere Informationen für jede Region hinzugefügt.",
      tr: "Her bölge için daha detaylı bilgi ekledik.",
      ar: "لقد أضفنا معلومات أكثر تفصيلاً لكل منطقة.",
      fr: "Nous avons ajouté des informations plus détaillées pour chaque région.",
      es: "Hemos añadido información más detallada para cada región.",
      pl: "Dodaliśmy bardziej szczegółowe informacje dla każdego regionu.",
      el: "Προσθέσαμε πιο λεπτομερείς πληροφορίες για κάθε περιοχή.",
      ro: "Am adăugat informații mai detaliate pentru fiecare regiune."
    },
    fullText: {
      en: "Detailed regional updates with all the latest information and requirements. Additional insights: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue.",
      uk: "Детальні оновлення регіонів з усією останньою інформацією та вимогами. Додаткові відомості: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue.",
      ru: "Подробные обновления регионов с последней информацией и требованиями. Дополнительная информация: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue.",
      de: "Ausführliche regionale Updates mit allen neuesten Informationen und Anforderungen. Zusätzliche Einblicke: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue.",
      tr: "En son bilgiler ve gereksinimlerle detaylı bölgesel güncellemeler. Ek bilgiler: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue.",
      ar: "تحديثات إقليمية مفصلة مع أحدث المعلومات والمتطلبات. رؤى إضافية: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue.",
      fr: "Mises à jour régionales détaillées avec toutes les dernières informations et exigences. Informations supplémentaires: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue.",
      es: "Actualizaciones regionales detalladas con toda la información y requisitos más recientes. Información adicional: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue.",
      pl: "Szczegółowe aktualizacje regionalne ze wszystkimi najnowszymi informacjami i wymaganiami. Dodatkowe informacje: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue.",
      el: "Λεπτομερείς περιφερειακές ενημερώσεις με όλες τις τελευταίες πληροφορίες και απαιτήσεις. Πρόσθετες πληροφορίες: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue.",
      ro: "Actualizări regionale detaliate cu toate informațiile și cerințele recente. Informații suplimentare: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue."
    },
    date: "20.03.2025",
  },
];

export default newsData;