// src/pages/StudyPlanPage/topics.js

// Сировинний список пріоритетних тем – 74 теми (51 "schwierige" та 23 "leichte")
// За бажанням доповни список додатковими темами або підтеми.
export const rawTopicsList = [
    // Schwierige Themen (51 тема)
    "Akutes Abdomen",
    "Akutes Koronarsyndrom",
    "Anaphylaktischer Schock",
    "Aortendissektion",
    "Appendizitis",
    "(optional – Ruhetag/Wiederholung)",
    "Asthma bronchiale",
    "Cholezystitis und Cholangitis",
    "COPD",
    "Pneumonie",
    "Pneumothorax",
    "(optional – Wiederholungstag)",
    "Reanimation",
    "Schlaganfall",
    "Schock",
    "Sepsis",
    "Thoraxschmerz",
    "Vorhofflimmern",
    "Akutes Nierenversagen",
    "Aneurysma der Aorta abdominalis",
    "(optional – Ruhetag/Wiederholung)",
    "Arterielle Hypertonie",
    "Bandscheibenvorfall",
    "Colitis ulcerosa",
    "COVID-19",
    "Delirium tremens",
    "Divertikulitis",
    "Endokarditis",
    "Gastroösophageale Refluxkrankheit",
    "Herzklappenerkrankungen",
    "Hirnblutung (intrazerebral)",
    "HIV/AIDS",
    "Hyperkaliämie",
    "Hypertensive Krise",
    "Hyperthyreose",
    "Hypothyreose",
    "Ikterus",
    "Kopfschmerzen",
    "Koronare Herzkrankheit",
    "Leberzirrhose",
    "Morbus Addison",
    "Morbus Crohn",
    "Myokarditis",
    "Perikarditis",
    "Periphere arterielle Verschlusskrankheit",
    "Polytrauma",
    "Pyelonephritis",
    "Schädel-Hirn-Trauma",
    "STIKO-Impfempfehlungen",
    "Subarachnoidalblutung",
    "Synkope",
    
    // Leichte Themen (23 тема)
    "Bronchialkarzinom",
    "Chronische Niereninsuffizienz",
    "Cushing-Syndrom",
    "Diabetes insipidus",
    "Gicht",
    "Kolorektales Karzinom",
    "Leistenhernie",
    "Leukämie (akut)",
    "Lymphome",
    "Malaria",
    "Mammakarzinom",
    "Morbus Parkinson",
    "Müdigkeit",
    "Multiple Sklerose",
    "Osteoporose",
    "Phäochromozytom",
    "Prostatakarzinom",
    "Rheumatoide Arthritis",
    "Rückenschmerzen",
    "Systemischer Lupus erythematodes",
    "Ulkuskrankheit",
    "Verbrennungen",
    "Vergiftungen"
  ];