// src/constants/DocumentTutorialtransaltion.js

const tutorialTranslations = {
  en: {
    steps: {
      mainTable: "This is the first table with the required documents for submitting an application.",
      header_apostile: "Apostille Header",
      header_notary: "Notary Header",
      header_translation: "Translation Header",
      header_ready_copies: "Ready Copies Header",
      header_sent: "Sent Header",
      header_links: "Links Header",
      secondTable: "Second Table",
      regionalLink: "Regional Link",
      optionalDocumentsSection: "Optional Documents Section",
      printButton: "Click here to print the list of documents.",
      // Мобільні кроки
      mobile: {
        firstTile: "Each document is contained in a separate tile, each has its own checkboxes.",
        secondTileCheckboxes: "These checkboxes indicate the status of the documents.",
        is_exist: "This checkbox indicates whether the document exists.",
        apostile: "This checkbox indicates whether the document has an apostille.",
        notary: "This checkbox indicates whether the document is notarized.",
        translation: "This checkbox indicates whether the document is translated.",
        ready_copies: "This checkbox indicates whether the document copies are ready.",
        sent: "This checkbox indicates whether the document has been sent.",
        documentSecondTile_3: "These links lead to documents according to the selected region.",
        optionalDocumentsSection: "These are optional documents that can be added to improve the approval.",
        printButton: "Click here to print the list of documents.",
      },
    },
  },
  uk: {
    steps: {
      mainTable: "Це перша таблиця з необхідними документами для подання заявки.",
      header_apostile: "Апостиль",
      header_notary: "Нотаріальне засвідчення",
      header_translation: "Переклад",
      header_ready_copies: "Готові копії",
      header_sent: "Надіслано",
      header_links: "Посилання",
      secondTable: "Друга таблиця",
      regionalLink: "Регіональні вимоги",
      optionalDocumentsSection: "Опціональні документи",
      printButton: "Натисніть тут, щоб надрукувати список документів.",
      mobile: {
        firstTile: "Кожен документ міститься в окремій плитці, кожен має свої чекбокси.",
        secondTileCheckboxes: "Ці чекбокси позначають статус документів.",
        is_exist: "Цей чекбокс позначає, чи документ наявний.",
        apostile: "Цей чекбокс позначає, чи документ має апостиль.",
        notary: "Цей чекбокс позначає, чи документ нотаріально завірений.",
        translation: "Цей чекбокс позначає, чи документ перекладено.",
        ready_copies: "Цей чекбокс позначає, чи готові копії документів.",
        sent: "Цей чекбокс позначає, чи документ відправлено.",
        documentSecondTile_3: "Ці лінки ведуть до документів відповідно до вибраного регіону.",
        optionalDocumentsSection: "Це опціональні документи для покращення апробації.",
        printButton: "Натисніть тут, щоб надрукувати список документів.",
      },
    },
  },
  ru: {
    steps: {
      mainTable: "Это первая таблица с необходимыми документами для подачи заявки.",
      header_apostile: "Апостиль",
      header_notary: "Нотариальное заверение",
      header_translation: "Перевод",
      header_ready_copies: "Готовые копии",
      header_sent: "Отправлено",
      header_links: "Ссылки",
      secondTable: "Вторая таблица",
      regionalLink: "Региональные требования",
      optionalDocumentsSection: "Дополнительные документы",
      printButton: "Нажмите здесь, чтобы распечатать список документов.",
      mobile: {
        firstTile: "Каждый документ содержится в отдельной плитке, у каждого есть свои чекбоксы.",
        secondTileCheckboxes: "Эти чекбоксы обозначают статус документов.",
        is_exist: "Этот чекбокс обозначает, есть ли документ.",
        apostile: "Этот чекбокс обозначает, есть ли апостиль на документе.",
        notary: "Этот чекбокс обозначает, нотариально ли заверен документ.",
        translation: "Этот чекбокс обозначает, переведен ли документ.",
        ready_copies: "Этот чекбокс обозначает, готовы ли копии документов.",
        sent: "Этот чекбокс обозначает, отправлен ли документ.",
        documentSecondTile_3: "Эти ссылки ведут к документам в соответствии с выбранным регионом.",
        optionalDocumentsSection: "Это дополнительные документы, которые можно приложить для улучшения апробации.",
        printButton: "Нажмите здесь, чтобы распечатать список документов.",
      },
    },
  },
  de: {
    steps: {
      mainTable: "Dies ist die erste Tabelle mit den erforderlichen Dokumenten für die Antragstellung.",
      header_apostile: "Apostille",
      header_notary: "Notarielle Beglaubigung",
      header_translation: "Übersetzung",
      header_ready_copies: "Fertige Kopien",
      header_sent: "Gesendet",
      header_links: "Links",
      secondTable: "Zweite Tabelle",
      regionalLink: "Regionale Anforderungen",
      optionalDocumentsSection: "Optionale Dokumente",
      printButton: "Klicken Sie hier, um die Dokumentenliste auszudrucken.",
      mobile: {
        firstTile: "Jedes Dokument befindet sich in einer separaten Kachel, jede hat eigene Checkboxen.",
        secondTileCheckboxes: "Diese Checkboxen zeigen den Status der Dokumente an.",
        is_exist: "Dieses Kontrollkästchen zeigt an, ob das Dokument vorhanden ist.",
        apostile: "Dieses Kontrollkästchen zeigt an, ob das Dokument eine Apostille hat.",
        notary: "Dieses Kontrollkästchen zeigt an, ob das Dokument notariell beglaubigt ist.",
        translation: "Dieses Kontrollkästchen zeigt an, ob das Dokument übersetzt ist.",
        ready_copies: "Dieses Kontrollkästchen zeigt an, ob Kopien des Dokuments bereit sind.",
        sent: "Dieses Kontrollkästchen zeigt an, ob das Dokument gesendet wurde.",
        documentSecondTile_3: "Diese Links führen zu Dokumenten gemäß der ausgewählten Region.",
        optionalDocumentsSection: "Dies sind optionale Dokumente, die zur Verbesserung der Anerkennung hinzugefügt werden können.",
        printButton: "Klicken Sie hier, um die Dokumentenliste auszudrucken.",
      },
    },
  },
};
  // Додайте інші мови за потребою

export default tutorialTranslations;