export const LANDS_INFO = [
   {
      id: 101,
      name: "Baden-Württemberg-Freiburg",
      key: "BadenWuerttembergFreiburg",
      desc: {
        en: "Baden-Württemberg-Freiburg is a subregion of the economically strong state in the southwest of Germany, a hub for engineering and the automotive industry, home to global players like Mercedes-Benz and Porsche in Stuttgart. The region is also known for its diverse landscape, stretching from the Black Forest to Lake Constance, offering a high quality of life and numerous cultural and nature-related activities. Additionally, it is famous for its culinary diversity, especially wines and regional specialties.",
        fr: "Bade-Wurtemberg-Freiburg est une sous-région de cet État économiquement fort situé dans le sud-ouest de l'Allemagne, un pôle d'ingénierie et de l'industrie automobile, abritant des acteurs mondiaux comme Mercedes-Benz et Porsche à Stuttgart. La région est également réputée pour son paysage diversifié, s'étendant de la Forêt-Noire au lac de Constance, offrant une haute qualité de vie et de nombreuses activités culturelles et naturelles. De plus, elle est célèbre pour sa diversité culinaire, en particulier ses vins et spécialités régionales.",
        es: "Baden-Wurtemberg-Freiburg es una subregión del estado económicamente fuerte en el suroeste de Alemania, un centro de ingeniería e industria automotriz, hogar de jugadores globales como Mercedes-Benz y Porsche en Stuttgart. La región también es conocida por su diverso paisaje, que se extiende desde la Selva Negra hasta el lago Constanza, ofreciendo una alta calidad de vida y numerosas actividades culturales y naturales. Además, es famosa por su diversidad culinaria, especialmente vinos y especialidades regionales.",
        ar: "بادن فورتمبرغ-فرايبورغ هي جزء من الولاية القوية اقتصادياً في جنوب غرب ألمانيا، ومركز للهندسة وصناعة السيارات، وموطن لشركات عالمية مثل مرسيدس بنز وبورشه في شتوتغارت. تشتهر المنطقة أيضاً بتنوع مناظرها الطبيعية الممتدة من الغابة السوداء وحتى بحيرة كونستانس، مما يوفر نوعية حياة عالية والعديد من الأنشطة الثقافية والطبيعية. بالإضافة إلى ذلك، تشتهر بتنوعها الطبخي، خاصة النبيذ والأطباق الإقليمية.",
        tr: "Baden-Württemberg-Freiburg, Almanya'nın güneybatısında bulunan ekonomik açıdan güçlü eyaletin bir alt bölgesidir; mühendislik ve otomotiv endüstrisinin merkezidir ve Stuttgart'taki Mercedes-Benz ve Porsche gibi küresel oyunculara ev sahipliği yapar. Bölge, Kara Orman'dan Konstanz Gölü'ne uzanan çeşitli manzarası, yüksek yaşam kalitesi ve çok sayıda kültürel ve doğa etkinliği ile de bilinir. Ayrıca özellikle şaraplar ve bölgesel yemekler gibi geniş bir mutfak çeşitliliği ile ünlüdür.",
        pl: "Baden-Württemberg-Freiburg to subregion w ekonomicznie silnym kraju związkowym w południowo-zachodnich Niemczech, będącym centrum inżynierii i przemysłu samochodowego, z takimi globalnymi graczami jak Mercedes-Benz i Porsche w Stuttgarcie. Region ten słynie również z różnorodnego krajobrazu rozciągającego się od Schwarzwaldu po Jezioro Bodeńskie, oferując wysoką jakość życia i liczne aktywności kulturalne oraz przyrodnicze. Dodatkowo, słynie z kulinarnej różnorodności, zwłaszcza win i regionalnych specjałów.",
        uk: "Баден-Вюртемберг-Фрайбург — це підрегіон економічно потужної землі на південному заході Німеччини, центру інженерії та автомобільної промисловості, де розташовані такі глобальні компанії, як Mercedes-Benz та Porsche у Штутгарті. Регіон також відомий різноманітним ландшафтом — від Шварцвальду до Боденського озера, що забезпечує високу якість життя та численні культурні й природні активності. Крім того, він славиться кулінарною різноманітністю, зокрема винами та регіональними стравами.",
        ru: "Баден-Вюртемберг-Фрайбург — это субрегион экономически сильной земли на юго-западе Германии, центра инженерии и автомобильной промышленности, где базируются глобальные компании, такие как Mercedes-Benz и Porsche в Штутгарте. Регион также известен своим разнообразным ландшафтом от Шварцвальда до Боденского озера, предлагая высокое качество жизни и множество культурных и природных развлечений. Кроме того, он славится своим кулинарным разнообразием, особенно винами и региональными блюдами.",
        de: "Baden-Württemberg-Freiburg ist eine Unterregion des wirtschaftlich starken Bundeslandes im Südwesten Deutschlands, einem Zentrum für Ingenieurwesen und Automobilindustrie mit globalen Playern wie Mercedes-Benz und Porsche in Stuttgart. Die Region ist auch für ihre vielfältige Landschaft bekannt, die vom Schwarzwald bis zum Bodensee reicht, und bietet eine hohe Lebensqualität sowie zahlreiche kulturelle und naturbezogene Aktivitäten. Darüber hinaus ist sie für ihre kulinarische Vielfalt berühmt, insbesondere für Weine und regionale Spezialitäten.",
        el: "Το Baden-Württemberg-Freiburg είναι μια υποπεριοχή του οικονομικά ισχυρού κρατιδίου στη νοτιοδυτική Γερμανία, κέντρο μηχανικής και αυτοκινητοβιομηχανίας, όπου φιλοξενούνται παγκόσμιες εταιρείες όπως η Mercedes-Benz και η Porsche στη Στουτγάρδη. Η περιοχή είναι επίσης γνωστή για το ποικιλόμορφο τοπίο της, που εκτείνεται από τον Μέλανα Δρυμό έως τη λίμνη Κωνσταντία, προσφέροντας υψηλή ποιότητα ζωής και πλήθος πολιτιστικών και φυσιολατρικών δραστηριοτήτων. Επιπλέον, φημίζεται για την πλούσια γαστρονομική της ποικιλία, ειδικά για τα κρασιά και τις τοπικές σπεσιαλιτέ.",
        ro: "Baden-Württemberg-Freiburg este o subregiune a landului cu o economie puternică din sud-vestul Germaniei, un centru pentru inginerie și industria auto, găzduind companii globale precum Mercedes-Benz și Porsche în Stuttgart. Regiunea este cunoscută și pentru peisajul său divers, care se întinde de la Pădurea Neagră până la Lacul Constance, oferind un nivel ridicat de trai și numeroase activități culturale și în natură. De asemenea, este renumită pentru diversitatea sa culinară, în special vinuri și specialități regionale."
      },
      main_link: "https://rp.baden-wuerttemberg.de/themen/bildung/ausbildung/seiten/arzt-ausland/",
      doctor_palat: "http://www.aerztekammer-bw.de"
   },
   {
      id: 102,
      name: "Baden-Württemberg-Karlsruhe",
      key: "BadenWuerttembergKarlsruhe",
      desc: {
        en: "Baden-Württemberg-Karlsruhe is a subregion of the economically strong state in the southwest of Germany, a hub for engineering and the automotive industry, home to global players like Mercedes-Benz and Porsche in Stuttgart. The region is also known for its diverse landscape, stretching from the Black Forest to Lake Constance, offering a high quality of life and numerous cultural and nature-related activities. Additionally, it is famous for its culinary diversity, especially wines and regional specialties.",
        fr: "Bade-Wurtemberg-Karlsruhe est une sous-région de cet État économiquement fort situé dans le sud-ouest de l'Allemagne, un pôle d'ingénierie et de l'industrie automobile, abritant des acteurs mondiaux comme Mercedes-Benz et Porsche à Stuttgart. La région est également réputée pour son paysage diversifié, s'étendant de la Forêt-Noire au lac de Constance, offrant une haute qualité de vie et de nombreuses activités culturelles et naturelles. De plus, elle est célèbre pour sa diversité culinaire, en particulier ses vins et spécialités régionales.",
        es: "Baden-Wurtemberg-Karlsruhe es una subregión del estado económicamente fuerte en el suroeste de Alemania, un centro de ingeniería e industria automotriz, hogar de jugadores globales como Mercedes-Benz y Porsche en Stuttgart. La región también es conocida por su diverso paisaje, que se extiende desde la Selva Negra hasta el lago Constanza, ofreciendo una alta calidad de vida y numerosas actividades culturales y naturales. Además, es famosa por su diversidad culinaria, especialmente vinos y especialidades regionales.",
        ar: "بادن فورتمبرغ-كارلسروه هي جزء من الولاية القوية اقتصادياً في جنوب غرب ألمانيا، ومركز للهندسة وصناعة السيارات، وموطن لشركات عالمية مثل مرسيدس بنز وبورشه في شتوتغارت. تشتهر المنطقة أيضاً بتنوع مناظرها الطبيعية الممتدة من الغابة السوداء وحتى بحيرة كونستانس، مما يوفر نوعية حياة عالية والعديد من الأنشطة الثقافية والطبيعية. بالإضافة إلى ذلك، تشتهر بتنوعها الطبخي، خاصة النبيذ والأطباق الإقليمية.",
        tr: "Baden-Württemberg-Karlsruhe, Almanya'nın güneybatısında bulunan ekonomik açıdan güçlü eyaletin bir alt bölgesidir; mühendislik ve otomotiv endüstrisinin merkezidir ve Stuttgart'taki Mercedes-Benz ve Porsche gibi küresel oyunculara ev sahipliği yapar. Bölge, Kara Orman'dan Konstanz Gölü'ne uzanan çeşitli manzarası, yüksek yaşam kalitesi ve kültürel/doğal etkinlikleriyle tanınır. Ayrıca özellikle şaraplar ve bölgesel yemekler gibi geniş bir mutfak çeşitliliği ile ünlüdür.",
        pl: "Baden-Württemberg-Karlsruhe to subregion w ekonomicznie silnym kraju związkowym w południowo-zachodnich Niemczech, będącym centrum inżynierii i przemysłu samochodowego, z takimi globalnymi graczami jak Mercedes-Benz i Porsche w Stuttgarcie. Region ten słynie również z różnorodnego krajobrazu rozciągającego się od Schwarzwaldu po Jezioro Bodeńskie, oferując wysoką jakość życia oraz liczne aktywności kulturalne i przyrodnicze. Dodatkowo, słynie z kulinarnej różnorodności, zwłaszcza win i regionalnych specjałów.",
        uk: "Баден-Вюртемберг-Карлсруе — це підрегіон економічно потужної землі на південному заході Німеччини, центру інженерії та автомобільної промисловості, де розташовані такі глобальні компанії, як Mercedes-Benz та Porsche у Штутгарті. Регіон відомий своїм різноманітним ландшафтом — від Шварцвальду до Боденського озера, що надає високу якість життя та багато культурних і природних активностей. Крім того, славиться кулінарною різноманітністю, особливо винами та регіональними стравами.",
        ru: "Баден-Вюртемберг-Карлсруэ — это субрегион экономически сильной земли на юго-западе Германии, центра инженерии и автомобильной промышленности, где базируются такие глобальные компании, как Mercedes-Benz и Porsche в Штутгарте. Регион известен разнообразным ландшафтом от Шварцвальда до Боденского озера, предлагая высокое качество жизни и богатые культурные и природные возможности. Кроме того, он славится своим кулинарным разнообразием, в частности винами и региональными блюдами.",
        de: "Baden-Württemberg-Karlsruhe ist eine Unterregion des wirtschaftlich starken Bundeslandes im Südwesten Deutschlands, einem Zentrum für Ingenieurwesen und Automobilindustrie mit globalen Playern wie Mercedes-Benz und Porsche in Stuttgart. Die Region ist für ihre vielfältige Landschaft vom Schwarzwald bis zum Bodensee bekannt und bietet eine hohe Lebensqualität sowie zahlreiche kulturelle und naturbezogene Aktivitäten. Darüber hinaus ist sie für ihre kulinarische Vielfalt berühmt, insbesondere für Weine und regionale Spezialitäten.",
        el: "Το Baden-Württemberg-Karlsruhe είναι μια υποπεριοχή του οικονομικά ισχυρού κρατιδίου στη νοτιοδυτική Γερμανία, κέντρο μηχανικής και αυτοκινητοβιομηχανίας, που φιλοξενεί παγκόσμιες εταιρείες όπως η Mercedes-Benz και η Porsche στη Στουτγάρδη. Η περιοχή φημίζεται επίσης για το ποικιλόμορφο τοπίο της, από τον Μέλανα Δρυμό έως τη λίμνη Κωνσταντία, προσφέροντας υψηλή ποιότητα ζωής και πολυάριθμες πολιτιστικές και φυσιολατρικές δραστηριότητες. Επιπλέον, είναι γνωστή για τη γαστρονομική της ποικιλομορφία, ειδικά τα κρασιά και τις τοπικές σπεσιαλιτέ.",
        ro: "Baden-Württemberg-Karlsruhe este o subregiune a landului cu o economie puternică din sud-vestul Germaniei, un centru pentru inginerie și industria auto, găzduind companii globale precum Mercedes-Benz și Porsche în Stuttgart. Regiunea se remarcă și prin peisajul său divers, care se întinde de la Pădurea Neagră până la Lacul Constance, oferind o calitate ridicată a vieții și numeroase activități culturale și în natură. De asemenea, este renumită pentru diversitatea culinară, în special vinuri și specialități regionale."
      },
      main_link: "https://rp.baden-wuerttemberg.de/themen/bildung/ausbildung/seiten/arzt-ausland/",
      doctor_palat: "http://www.aerztekammer-bw.de"
   },
   {
      id: 103,
      name: "Baden-Württemberg-Stuttgart",
      key: "BadenWuerttembergStuttgart",
      desc: {
        en: "Baden-Württemberg-Stuttgart is a subregion of the economically strong state in the southwest of Germany, a hub for engineering and the automotive industry, home to global players like Mercedes-Benz and Porsche in Stuttgart itself. The region is also known for its diverse landscape, stretching from the Black Forest to Lake Constance, offering a high quality of life and numerous cultural and nature-related activities. Additionally, it is famous for its culinary diversity, especially wines and regional specialties.",
        fr: "Bade-Wurtemberg-Stuttgart est une sous-région de cet État économiquement fort situé dans le sud-ouest de l'Allemagne, un pôle d'ingénierie et de l'industrie automobile, abritant des acteurs mondiaux comme Mercedes-Benz et Porsche dans la ville de Stuttgart. La région est également réputée pour son paysage diversifié, s'étendant de la Forêt-Noire au lac de Constance, offrant une haute qualité de vie et de nombreuses activités culturelles et naturelles. De plus, elle est célèbre pour sa diversité culinaire, en particulier ses vins et spécialités régionales.",
        es: "Baden-Wurtemberg-Stuttgart es una subregión del estado económicamente fuerte en el suroeste de Alemania, un centro de ingeniería e industria automotriz, hogar de jugadores globales como Mercedes-Benz y Porsche en la propia Stuttgart. La región también es conocida por su diverso paisaje, que se extiende desde la Selva Negra hasta el lago Constanza, ofreciendo una alta calidad de vida y numerosas actividades culturales y naturales. Además, es famosa por su diversidad culinaria, especialmente vinos y especialidades regionales.",
        ar: "بادن فورتمبرغ-شتوتغارت هي جزء من الولاية القوية اقتصادياً في جنوب غرب ألمانيا، ومركز للهندسة وصناعة السيارات، وموطن لشركات عالمية مثل مرسيدس بنز وبورشه في مدينة شتوتغارت نفسها. تشتهر المنطقة أيضاً بتنوع مناظرها الطبيعية الممتدة من الغابة السوداء إلى بحيرة كونستانس، مما يوفر جودة حياة عالية والعديد من الأنشطة الثقافية والطبيعية. بالإضافة إلى ذلك، تشتهر بتنوعها الطبخي، خاصة النبيذ والأطباق الإقليمية.",
        tr: "Baden-Württemberg-Stuttgart, Almanya'nın güneybatısındaki ekonomik açıdan güçlü eyaletin bir alt bölgesidir ve mühendislik ile otomotiv endüstrisinin merkezlerinden biri olup, özellikle Stuttgart şehrindeki Mercedes-Benz ve Porsche gibi küresel oyunculara ev sahipliği yapar. Bölge, Kara Orman'dan Konstanz Gölü'ne uzanan zengin doğal çeşitliliği, yüksek yaşam kalitesi ve çok sayıda kültürel/doğal aktivitesiyle tanınır. Ayrıca şaraplar ve bölgesel spesiyaliteler gibi mutfak çeşitliliğiyle ünlüdür.",
        pl: "Baden-Württemberg-Stuttgart to subregion w ekonomicznie silnym kraju związkowym w południowo-zachodnich Niemczech, będącym centrum inżynierii i przemysłu samochodowego, zwłaszcza w samym Stuttgarcie, gdzie znajdują się Mercedes-Benz i Porsche. Region ten znany jest również z różnorodnego krajobrazu – od Schwarzwaldu po Jezioro Bodeńskie – oferując wysoką jakość życia i liczne atrakcje kulturalne oraz przyrodnicze. Ponadto słynie z kulinarnej różnorodności, w tym win i regionalnych potraw.",
        uk: "Баден-Вюртемберг-Штутгарт — це підрегіон економічно потужної землі на південному заході Німеччини, центру інженерії та автомобільної промисловості, де в самому Штутгарті розташовані Mercedes-Benz і Porsche. Регіон відомий також різноманітним ландшафтом — від Шварцвальду до Боденського озера, що забезпечує високу якість життя й безліч культурних і природних заходів. Крім того, він знаменитий кулінарною різноманітністю, зокрема винами та регіональними спеціальними стравами.",
        ru: "Баден-Вюртемберг-Штутгарт — это субрегион экономически сильной земли на юго-западе Германии, центр инженерии и автомобильной промышленности, где в самом Штутгарте расположены такие глобальные компании, как Mercedes-Benz и Porsche. Регион также славится разнообразным ландшафтом, простирающимся от Шварцвальда до Боденского озера, высоким качеством жизни и множеством культурных и природных возможностей. Кроме того, он известен своим кулинарным разнообразием, особенно винами и региональными специалитетами.",
        de: "Baden-Württemberg-Stuttgart ist eine Unterregion des wirtschaftlich starken Bundeslandes im Südwesten Deutschlands und gilt als Zentrum für Ingenieurwesen und Automobilindustrie, insbesondere durch globale Player wie Mercedes-Benz und Porsche in Stuttgart selbst. Die Region ist auch für ihre vielfältige Landschaft bekannt, die vom Schwarzwald bis zum Bodensee reicht, und bietet eine hohe Lebensqualität sowie zahlreiche kulturelle und naturbezogene Aktivitäten. Darüber hinaus ist sie für ihre kulinarische Vielfalt berühmt, insbesondere Weine und regionale Spezialitäten.",
        el: "Το Baden-Württemberg-Stuttgart είναι μια υποπεριοχή του οικονομικά ισχυρού κρατιδίου στη νοτιοδυτική Γερμανία, κέντρο μηχανικής και αυτοκινητοβιομηχανίας, ιδιαίτερα με εταιρείες όπως η Mercedes-Benz και η Porsche στην ίδια τη Στουτγάρδη. Η περιοχή αυτή φημίζεται για το ποικιλόμορφο τοπίο της, από τον Μέλανα Δρυμό μέχρι τη λίμνη Κωνσταντία, προσφέροντας υψηλή ποιότητα ζωής και πολλές πολιτιστικές και φυσικές δραστηριότητες. Επιπλέον, είναι γνωστή για τη γαστρονομική της ποικιλία, ειδικά σε ό,τι αφορά το κρασί και τις τοπικές σπεσιαλιτέ.",
        ro: "Baden-Württemberg-Stuttgart este o subregiune a landului cu o economie puternică din sud-vestul Germaniei, un centru pentru inginerie și industria auto, găzduind în orașul Stuttgart companii globale precum Mercedes-Benz și Porsche. Regiunea este cunoscută și pentru peisajul său divers, care se întinde de la Pădurea Neagră până la Lacul Constance, oferind o calitate ridicată a vieții și numeroase activități culturale și în natură. De asemenea, este renumită pentru diversitatea culinară, în special vinuri și specialități regionale."
      },
      main_link: "https://rp.baden-wuerttemberg.de/themen/bildung/ausbildung/seiten/arzt-ausland/",
      doctor_palat: "http://www.aerztekammer-bw.de"
   },
   {
      id: 104,
      name: "Baden-Württemberg-Reutlingen",
      key: "BadenWuerttembergReutlingen",
      desc: {
        en: "Baden-Württemberg-Reutlingen is a subregion of the economically strong state in the southwest of Germany, a hub for engineering and the automotive industry, home to global players like Mercedes-Benz and Porsche in Stuttgart. The region is also known for its diverse landscape, stretching from the Black Forest to Lake Constance, offering a high quality of life and numerous cultural and nature-related activities. Additionally, it is famous for its culinary diversity, especially wines and regional specialties.",
        fr: "Bade-Wurtemberg-Reutlingen est une sous-région de cet État économiquement fort situé dans le sud-ouest de l'Allemagne, un pôle d'ingénierie et de l'industrie automobile, abritant des acteurs mondiaux comme Mercedes-Benz et Porsche à Stuttgart. La région est également réputée pour son paysage diversifié, s'étendant de la Forêt-Noire au lac de Constance, offrant une haute qualité de vie et de nombreuses activités culturelles et naturelles. De plus, elle est célèbre pour sa diversité culinaire, en particulier ses vins et spécialités régionales.",
        es: "Baden-Wurtemberg-Reutlingen es una subregión del estado económicamente fuerte en el suroeste de Alemania, un centro de ingeniería e industria automotriz, hogar de jugadores globales como Mercedes-Benz y Porsche en Stuttgart. La región también es conocida por su diverso paisaje, que se extiende desde la Selva Negra hasta el lago Constanza, ofreciendo una alta calidad de vida y numerosas actividades culturales y naturales. Además, es famosa por su diversidad culinaria, especialmente vinos y especialidades regionales.",
        ar: "بادن فورتمبرغ-رويتلينغن هي جزء من الولاية القوية اقتصادياً في جنوب غرب ألمانيا، ومركز للهندسة وصناعة السيارات، وموطن لشركات عالمية مثل مرسيدس بنز وبورشه في شتوتغارت. تشتهر المنطقة أيضاً بتنوع مناظرها الطبيعية الممتدة من الغابة السوداء إلى بحيرة كونستانس، مما يوفر نوعية حياة عالية والعديد من الأنشطة الثقافية والطبيعية. بالإضافة إلى ذلك، تشتهر بتنوعها الطبخي، خاصة النبيذ والأطباق الإقليمية.",
        tr: "Baden-Württemberg-Reutlingen, Almanya'nın güneybatısındaki ekonomik açıdan güçlü eyaletin bir alt bölgesidir; mühendislik ve otomotiv endüstrisinin merkezidir ve Stuttgart'taki Mercedes-Benz ve Porsche gibi küresel şirketlere ev sahipliği yapar. Kara Orman'dan Konstanz Gölü'ne uzanan çeşitli manzarası, yüksek yaşam kalitesi ve kültürel/doğal faaliyetleriyle tanınır. Ayrıca şaraplar ve bölgesel spesiyaliteler gibi geniş bir mutfak çeşitliliğine sahiptir.",
        pl: "Baden-Württemberg-Reutlingen to subregion w ekonomicznie silnym kraju związkowym w południowo-zachodnich Niemczech, będącym centrum inżynierii i przemysłu samochodowego, z globalnymi firmami takimi jak Mercedes-Benz i Porsche w Stuttgarcie. Region ten jest również znany z różnorodnego krajobrazu rozciągającego się od Schwarzwaldu po Jezioro Bodeńskie, oferując wysoką jakość życia i wiele atrakcji kulturalnych i przyrodniczych. Ponadto słynie z kulinarnej różnorodności, w tym z win i regionalnych specjałów.",
        uk: "Баден-Вюртемберг-Ройтлінген — це підрегіон економічно потужної землі на південному заході Німеччини, центру інженерії та автомобільної промисловості, де базуються глобальні компанії на кшталт Mercedes-Benz і Porsche в Штутгарті. Регіон також відомий своїм різноманітним ландшафтом від Шварцвальду до Боденського озера, пропонуючи високу якість життя та численні культурні й природні заходи. Крім того, він славиться своєю кулінарною різноманітністю, особливо винами та регіональними стравами.",
        ru: "Баден-Вюртемберг-Ройтлинген — это субрегион экономически сильной земли на юго-западе Германии, центра инженерии и автомобильной промышленности, где в Штутгарте расположены такие крупные компании, как Mercedes-Benz и Porsche. Регион известен своим разнообразным ландшафтом — от Шварцвальда до Боденского озера, предлагая высокое качество жизни и множество культурных и природных мероприятий. Кроме того, он славится своим кулинарным разнообразием, особенно винами и региональными блюдами.",
        de: "Baden-Württemberg-Reutlingen ist eine Unterregion des wirtschaftlich starken Bundeslandes im Südwesten Deutschlands, einem Zentrum für Ingenieurwesen und Automobilindustrie mit globalen Unternehmen wie Mercedes-Benz und Porsche in Stuttgart. Die Region zeichnet sich durch ihre vielfältige Landschaft vom Schwarzwald bis zum Bodensee aus und bietet eine hohe Lebensqualität sowie zahlreiche kulturelle und naturbezogene Aktivitäten. Außerdem ist sie für ihre kulinarische Vielfalt bekannt, insbesondere Weine und regionale Spezialitäten.",
        el: "Το Baden-Württemberg-Reutlingen είναι μια υποπεριοχή του οικονομικά ισχυρού ομόσπονδου κρατιδίου στη νοτιοδυτική Γερμανία, όπου δραστηριοποιούνται μεγάλες εταιρείες μηχανικής και αυτοκινητοβιομηχανίας, όπως η Mercedes-Benz και η Porsche στη Στουτγάρδη. Η περιοχή φημίζεται για το ποικιλόμορφο τοπίο της, από τον Μέλανα Δρυμό μέχρι τη λίμνη Κωνσταντία, προσφέροντας υψηλή ποιότητα ζωής και πλήθος πολιτιστικών καθώς και φυσιολατρικών δραστηριοτήτων. Επιπλέον, είναι διάσημη για την ποικιλία της σε γαστρονομικά είδη, ιδιαίτερα τα κρασιά και τις τοπικές σπεσιαλιτέ.",
        ro: "Baden-Württemberg-Reutlingen este o subregiune a landului cu o economie puternică din sud-vestul Germaniei, recunoscută pentru inginerie și industria auto, găzduind companii globale precum Mercedes-Benz și Porsche în Stuttgart. Regiunea este de asemenea cunoscută pentru peisajul său variat, care se întinde de la Pădurea Neagră până la Lacul Constance, oferind o calitate ridicată a vieții și numeroase activități culturale și în natură. În plus, este faimoasă pentru diversitatea culinară, în special vinuri și specialități regionale."
      },
      main_link: "https://rp.baden-wuerttemberg.de/themen/bildung/ausbildung/seiten/arzt-ausland/",
      doctor_palat: "http://www.aerztekammer-bw.de"
   },
   {
      id: 2,
      name: "Bayern",
      key: "Bayern",
      desc: {
         en: "Bavaria is Germany's largest state, rich in cultural identity with strong traditions in lederhosen, dirndls, and festivals like Munich's Oktoberfest. Its economy is marked by technology, the automotive industry, and engineering, with cities like Munich and Nuremberg as key economic centers. The stunning Alpine landscape, historical castles, and clear lakes provide ample leisure and recreation opportunities.",
         fr: "La Bavière est le plus grand État d'Allemagne, riche en identité culturelle avec de fortes traditions en culottes de peau, dirndls et festivals comme l'Oktoberfest de Munich. Son économie est marquée par la technologie, l'industrie automobile et l'ingénierie, avec des villes comme Munich et Nuremberg comme principaux centres économiques. Le magnifique paysage alpin, les châteaux historiques et les lacs clairs offrent de nombreuses possibilités de loisirs et de détente.",
         es: "Baviera es el estado más grande de Alemania, rico en identidad cultural con fuertes tradiciones en pantalones de cuero, dirndls y festivales como el Oktoberfest de Munich. Su economía se caracteriza por la tecnología, la industria automotriz y la ingeniería, con ciudades como Munich y Nuremberg como centros económicos clave. El impresionante paisaje alpino, los castillos históricos y los lagos cristalinos ofrecen amplias oportunidades de ocio y recreación.",
         ar: "بافاريا هي أكبر ولاية في ألمانيا، غنية بالهوية الثقافية مع تقاليد قوية في اللباس الجلدي والدرندلز، والمهرجانات مثل أوكتوبرفيست في ميونيخ. اقتصادها يتميز بالتكنولوجيا وصناعة السيارات والهندسة، مع مدن مثل ميونيخ ونورمبرغ كمراكز اقتصادية رئيسية. يوفر المناظر الطبيعية الجبلية الخلابة والقلاع التاريخية والبحيرات الصافية فرص ترفيه وترفيه وفيرة.",
         tr: "Bavyera, Almanya'nın en büyük eyaletidir ve kültürel kimlik açısından lederhosen, dirndl ve Münih Oktoberfest gibi festivallerle güçlü geleneklere sahiptir. Ekonomisi teknoloji, otomotiv endüstrisi ve mühendislikle belirlenir; Münih ve Nürnberg gibi şehirler önemli ekonomik merkezlerdir. Büyüleyici Alp manzarası, tarihi kaleler ve berrak göller bolca dinlenme ve rekreasyon fırsatı sunar.",
         pl: "Bawaria to największy kraj związkowy Niemiec, bogaty w tożsamość kulturową, z silnymi tradycjami w noszeniu szortów, dirndlów i festiwali, takich jak Oktoberfest w Monachium. Jej gospodarka charakteryzuje się technologią, przemysłem motoryzacyjnym i inżynierią, a miasta takie jak Monachium i Norymberga są kluczowymi centrami gospodarczymi. Zachwycający krajobraz alpejski, historyczne zamki i czyste jeziora zapewniają liczne możliwości wypoczynku i rekreacji.",
         uk: "Баварія - найбільший штат Німеччини, що багатий на культурну ідентичність зі сильними традиціями у ледерхозені, дірндлях та святкуваннях, таких як Мюнхенський фестиваль пива Октоберфест. Її економіка характеризується технологіями, автомобільною промисловістю та інженерією, а такі міста, як Мюнхен і Нюрнберг, є ключовими економічними центрами. Дивовижний альпійський ландшафт, історичні замки та чисті озера надають безліч можливостей для відпочинку та розваг.",
         ru: "Бавария - крупнейший земной край Германии, богатый культурной идентичностью с сильными традициями в ледерхозене, дирндлях и фестивалях, таких как Октоберфест в Мюнхене. Ее экономика характеризуется технологиями, автомобильной промышленностью и инженерией, а такие города, как Мюнхен и Нюрнберг, являются ключевыми экономическими центрами. Потрясающий альпийский пейзаж, исторические замки и чистые озера предоставляют массу возможностей для отдыха и рекреации.",
         de: "Bayern: Bayern ist das größte Bundesland Deutschlands und reich an kultureller Identität, mit einer starken Tradition in Lederhosen, Dirndl und Volksfesten wie dem Oktoberfest in München. Die bayerische Wirtschaft ist von Technologie, Automobilindustrie und Maschinenbau geprägt, mit Städten wie München und Nürnberg als wichtige Wirtschaftszentren. Bayerns atemberaubende Alpenlandschaft, historische Schlösser und klare Seen bieten zahlreiche Möglichkeiten für Freizeit und Erholung.",
         el: "Η Βαυαρία είναι το μεγαλύτερο ομόσπονδο κρατίδιο της Γερμανίας, πλούσιο σε πολιτιστική ταυτότητα με ισχυρές παραδόσεις σε lederhosen, dirndl και φεστιβάλ όπως το Oktoberfest του Μονάχου. Η οικονομία της χαρακτηρίζεται από την τεχνολογία, τη βιομηχανία αυτοκινήτων και τη μηχανολογία, με πόλεις όπως το Μόναχο και η Νυρεμβέργη ως σημαντικά οικονομικά κέντρα. Το εκπληκτικό αλπικό τοπίο, τα ιστορικά κάστρα και οι καθαρές λίμνες προσφέρουν άφθονες ευκαιρίες αναψυχής.",
         ro: "Bavaria este cel mai mare land al Germaniei, bogat în identitate culturală, cu tradiții puternice în costum popular (lederhosen, dirndl) și festivaluri precum Oktoberfestul din München. Economia sa este marcată de tehnologie, industria auto și inginerie, cu orașe precum München și Nürnberg ca importante centre economice. Peisajul alpin impresionant, castelele istorice și lacurile limpezi oferă numeroase oportunități de agrement și recreere."
      },
      main_link:
         "https://rp.baden-wuerttemberg.de/themen/bildung/ausbildung/seiten/arzt-ausland/",
      doctor_palat:"http://www.blaek.de"
   },
   {
      id: 3,
      name: "Berlin",
      key: "Berlin",
      desc: {
         de: "Berlin: Als Hauptstadt Deutschlands ist Berlin ein pulsierendes Zentrum für Politik, Kultur und Geschichte, das Besucher und Einwohner mit seiner dynamischen Atmosphäre anzieht. Die Stadt ist bekannt für ihre vielfältige Kunstszene, lebendige Nachtleben und zahlreichen Museen, die die bewegte Geschichte Berlins erzählen. Berlin ist auch ein bedeutendes Startup-Ökosystem und zieht Unternehmen aus den Bereichen Technologie, Medien und Kreativwirtschaft an.",
         en: "As Germany's capital, Berlin is a vibrant center for politics, culture, and history, attracting visitors and residents with its dynamic atmosphere. The city is renowned for its diverse art scene, lively nightlife, and numerous museums that narrate Berlin's turbulent history. It's also a significant startup ecosystem, drawing companies in technology, media, and creative industries.",
         fr: "Berlin : Capitale de l'Allemagne, Berlin est un centre dynamique pour la politique, la culture et l'histoire, attirant les visiteurs et les résidents avec son atmosphère dynamique. La ville est renommée pour sa scène artistique diversifiée, sa vie nocturne animée et ses nombreux musées qui racontent l'histoire tourmentée de Berlin. C'est aussi un écosystème de start-up important, attirant des entreprises dans les domaines de la technologie, des médias et des industries créatives.",
         es: "Berlín: Como capital de Alemania, Berlín es un centro vibrante de política, cultura e historia, que atrae a visitantes y residentes con su atmósfera dinámica. La ciudad es conocida por su diversa escena artística, animada vida nocturna y numerosos museos que narran la turbulenta historia de Berlín. También es un ecosistema de startups significativo, atrayendo empresas en tecnología, medios de comunicación e industrias creativas.",
         ar: "برلين: بصفتها عاصمة ألمانيا، تعتبر برلين مركزًا نابضًا بالحياة للسياسة والثقافة والتاريخ، مما يجذب الزوار والسكان بأجوائها الديناميكية. تشتهر المدينة بمشهدها الفني المتنوع، وحياتها الليلية النابضة بالحياة، والعديد من المتاحف التي تحكي تاريخ برلين العاصف. كما أنها نظام بدء تشغيل مهم، يجذب الشركات في مجال التكنولوجيا ووسائل الإعلام والصناعات الإبداعية.",
         tr: "Berlin: Almanya'nın başkenti olarak Berlin, dinamik atmosferiyle politika, kültür ve tarih için canlı bir merkezdir ve ziyaretçileri ve sakinleri çeker. Şehir, çeşitli sanat sahnesi, canlı gece hayatı ve Berlin'in türbülanslı tarihini anlatan birçok müzesi ile ünlüdür. Ayrıca, teknoloji, medya ve yaratıcı endüstrilerdeki şirketleri çeken önemli bir başlangıç ekosistemidir.",
         pl: "Berlin: Jako stolica Niemiec, Berlin jest dynamicznym centrum polityki, kultury i historii, przyciągającym odwiedzających i mieszkańców swoją dynamiczną atmosferą. Miasto słynie z różnorodnej sceny artystycznej, tętniącego życia nocnego i licznych muzeów opowiadających burzliwą historię Berlina. Jest także znaczącym ekosystemem startupów, przyciągającym firmy z branży technologicznej, medialnej i kreatywnej.",
         uk: "Берлін: Як столиця Німеччини, Берлін є живим центром політики, культури та історії, який приваблює відвідувачів і мешканців своєю динамічною атмосферою. Місто відоме своєю різноманітною художньою сценою, активним нічним життям та численними музеями, які розповідають про турбулентну історію Берліна. Також це значний екосистема стартапів, яка привертає компанії в галузі технологій, медіа та креативних індустрій.",
         ru: "Берлин: столица Германии, яркий центр политики, культуры и истории, привлекающий посетителей и жителей своей динамичной атмосферой. Город знаменит своей разнообразной художественной сценой, оживленной ночной жизнью и множеством музеев, рассказывающих о бурной истории Берлина. Он также значительный экосистема стартапов, привлекающая компании в области технологий, медиа и креативных отраслей.",
         el: "Βερολίνο: Ως πρωτεύουσα της Γερμανίας, το Βερολίνο είναι ένα ζωντανό κέντρο πολιτικής, πολιτισμού και ιστορίας, προσελκύοντας επισκέπτες και κατοίκους με τη δυναμική του ατμόσφαιρα. Η πόλη είναι γνωστή για τη διαφορετική καλλιτεχνική σκηνή, την έντονη νυχτερινή ζωή και τα πολυάριθμα μουσεία που διηγούνται την ταραχώδη ιστορία του Βερολίνου. Αποτελεί επίσης ένα σημαντικό οικοσύστημα νεοφυών επιχειρήσεων, προσελκύοντας εταιρείες τεχνολογίας, μέσων ενημέρωσης και δημιουργικών βιομηχανιών.",
         ro: "Berlin: Fiind capitala Germaniei, Berlin este un centru dinamic pentru politică, cultură și istorie, atrăgând vizitatori și rezidenți cu atmosfera sa energică. Orașul este renumit pentru scena artistică diversă, viața de noapte intensă și numeroasele muzee care ilustrează istoria turbulentă a Berlinului. De asemenea, este un ecosistem important pentru startup-uri, atrăgând companii din domeniile tehnologiei, media și industriilor creative."
      },
      main_link: "https://service.berlin.de/dienstleistung/331391/",
      doctor_palat:"http://www.aekb.de"
   },
   {
      id: 4,
      name: "Brandenburg",
      key: "Brandenburg",
      desc: {
         de: "Brandenburg: Umschließt die Hauptstadt Berlin und ist geprägt von ausgedehnten Naturlandschaften, darunter zahlreiche Seen, Flüsse und Wälder, die es zu einem beliebten Erholungsgebiet machen. Historische Städte wie Potsdam, mit seinen preußischen Schlössern und Gärten, bieten kulturellen Reichtum. Brandenburgs Wirtschaft profitiert von der Nähe zu Berlin, mit einem Fokus auf Landwirtschaft, erneuerbare Energien und Tourismus.",
         en: "Brandenburg: Encircling the capital Berlin, Brandenburg is characterized by extensive natural landscapes, including numerous lakes, rivers, and forests, making it a popular recreational area. Historical cities like Potsdam, with its Prussian palaces and gardens, offer cultural richness. Brandenburg's economy benefits from its proximity to Berlin, with a focus on agriculture, renewable energies, and tourism.",
         fr: "Brandebourg : Enveloppant la capitale Berlin, le Brandebourg est caractérisé par des paysages naturels étendus, comprenant de nombreux lacs, rivières et forêts, ce qui en fait une zone récréative populaire. Des villes historiques comme Potsdam, avec ses palais prussiens et ses jardins, offrent une richesse culturelle. L'économie du Brandebourg bénéficie de sa proximité avec Berlin, avec un accent sur l'agriculture, les énergies renouvelables et le tourisme.",
         es: "Brandenburgo: Rodeando la capital Berlín, Brandenburgo se caracteriza por extensos paisajes naturales, que incluyen numerosos lagos, ríos y bosques, lo que lo convierte en un área recreativa popular. Ciudades históricas como Potsdam, con sus palacios y jardines prusianos, ofrecen riqueza cultural. La economía de Brandenburgo se beneficia de su proximidad a Berlín, con un enfoque en la agricultura, las energías renovables y el turismo.",
         ar: "براندنبورغ: تحيط بالعاصمة برلين، ويتميز براندنبورغ بمناظر طبيعية واسعة تشمل العديد من البحيرات والأنهار والغابات، مما يجعلها منطقة ترفيهية شعبية. المدن التاريخية مثل بوتسدام، مع قصورها وحدائقها البروسية، تقدم ثراء ثقافيًا. تستفيد اقتصادات براندنبورغ من قربها من برلين، مع التركيز على الزراعة والطاقة المتجددة والسياحة.",
         tr: "Brandenburg: Başkent Berlin'i saran Brandenburg, çok sayıda göl, nehir ve ormanı içeren geniş doğal manzaralarıyla tanınır ve bu da onu popüler bir dinlenme alanı haline getirir. Potsdam gibi tarihi şehirler, Prusya sarayları ve bahçeleriyle kültürel zenginlik sunar. Brandenburg ekonomisi, tarım, yenilenebilir enerjiler ve turizm üzerine odaklanarak Berlin'e olan yakınlığından faydalanır.",
         pl: "Brandenburgia: Okalającą stolicę Berlin, Brandenburgię charakteryzują rozległe krajobrazy naturalne, obejmujące liczne jeziora, rzeki i lasy, co czyni ją popularnym obszarem rekreacyjnym. Historyczne miasta, takie jak Poczdam, ze swoimi pałacami i ogrodami pruskimi, oferują bogactwo kulturowe. Gospodarka Brandenburgii korzysta z bliskości Berlina, koncentrując się na rolnictwie, energiach odnawialnych i turystyce.",
         uk: "Бранденбург: Охоплюючи столицю Берлін, Бранденбург відзначається обширними природними ландшафтами, включаючи численні озера, річки та ліси, що робить його популярним місцем відпочинку. Історичні міста, такі як Потсдам, з його пруськими палацами та садами, пропонують культурне розмаїття. Економіка Бранденбургу користується своєю близькістю до Берліна, з фокусом на сільському господарстві, відновлюваній енергетиці та туризмі.",
         ru: "Бранденбург: Окружающий столицу Берлин, Бранденбург характеризуется обширными природными пейзажами, включая множество озер, рек и лесов, что делает его популярным местом отдыха. Исторические города, такие как Потсдам, с его прусскими дворцами и садами, предлагают культурное разнообразие. Экономика Бранденбурга получает выгоду от близости к Берлину, с акцентом на сельском хозяйстве, возобновляемых источниках энергии и туризме.",
         el: "Το Βρανδεμβούργο: Περιβάλλει την πρωτεύουσα Βερολίνο και χαρακτηρίζεται από εκτεταμένα φυσικά τοπία, με πολλά λίμνες, ποτάμια και δάση, κάνοντάς το ένα δημοφιλές μέρος αναψυχής. Ιστορικές πόλεις, όπως το Πότσνταμ, με τα πρωσικά του ανάκτορα και κήπους, προσφέρουν πολιτιστικό πλούτο. Η οικονομία του Βρανδεμβούργου επωφελείται από την εγγύτητα στο Βερολίνο, με έμφαση στη γεωργία, τις ανανεώσιμες πηγές ενέργειας και τον τουρισμό.",
         ro: "Brandenburg: Încercuind capitala Berlin, Brandenburg se caracterizează prin peisaje naturale vaste, cu numeroase lacuri, râuri și păduri, ceea ce îl face o zonă populară pentru recreere. Orașe istorice precum Potsdam, cu palatele și grădinile sale prusace, oferă bogăție culturală. Economia Brandenburgului beneficiază de proximitatea față de Berlin, concentrându-se pe agricultură, energii regenerabile și turism."
      },
      main_link:
         "https://lavg.brandenburg.de/lavg/de/gesundheit/akademische-heilberufe/anerkennung-auslaendischer-ausbildung/#",
      doctor_palat:"http://www.laekb.de"
   },
   {
      id: 5,
      name: "Bremen",
      key: "Bremen",
      desc: {
         de: "Bremen: Dieses kleine, aber geschichtsträchtige Bundesland besteht aus den zwei Städten Bremen und Bremerhaven und spielt eine wichtige Rolle in Deutschlands Handelsgeschichte. Bremen ist bekannt für sein gut erhaltenes mittelalterliches Stadtzentrum, den Bremer Stadtmusikanten und Weltraumforschungseinrichtungen. Bremerhaven ist ein wichtiger Seehafen mit einem maritimen Museumskomplex, der die Seefahrtsgeschichte der Region dokumentiert.",
         en: "Bremen: This small but historically rich federal state consists of two cities, Bremen and Bremerhaven, and plays an important role in Germany's trading history. Bremen is known for its well-preserved medieval city center, the Bremen Town Musicians, and space research facilities. Bremerhaven is a significant seaport with a maritime museum complex documenting the maritime history of the region.",
         fr: "Brême : Ce petit État fédéral, mais historiquement riche, se compose de deux villes, Brême et Bremerhaven, et joue un rôle important dans l'histoire commerciale de l'Allemagne. Brême est connue pour son centre-ville médiéval bien préservé, les musiciens de la ville de Brême et les installations de recherche spatiale. Bremerhaven est un port maritime important avec un complexe de musées maritimes documentant l'histoire maritime de la région.",
         es: "Bremen: Este pequeño pero históricamente rico estado federado consta de dos ciudades, Bremen y Bremerhaven, y desempeña un papel importante en la historia comercial de Alemania. Bremen es conocida por su centro histórico medieval bien conservado, los músicos de la ciudad de Bremen y las instalaciones de investigación espacial. Bremerhaven es un puerto marítimo significativo con un complejo de museos marítimos que documenta la historia marítima de la región.",
         ar: "بريمن: يتألف هذا الدولة الفدرالية الصغيرة ولكنها غنية تاريخيًا من مدينتين، بريمن وبريمرهافن، ويلعب دورًا هامًا في تاريخ التجارة في ألمانيا. بريمن مشهورة بمركزها التاريخي المحافظ جيدًا من العصور الوسطى، وموسيقيو مدينة بريمن، ومرافق البحث الفضائي. بريمرهافن هي ميناء بحري هام يضم مجمع متحفي بحري يوثق تاريخ الملاحة في المنطقة.",
         tr: "Bremen: Bu küçük ancak tarih açısından zengin federal eyalet, Bremen ve Bremerhaven olmak üzere iki şehirden oluşur ve Almanya'nın ticari tarihinde önemli bir rol oynar. Bremen, iyi korunmuş ortaçağ şehir merkezi, Bremen Kent Müzisyenleri ve uzay araştırma tesisleri ile tanınır. Bremerhaven, bölgenin denizcilik tarihini belgeleyen bir denizcilik müzesi kompleksi olan önemli bir deniz limanıdır.",
         pl: "Brema: Ten mały, ale bogaty historycznie kraj związkowy składa się z dwóch miast, Brema i Bremerhaven, i odgrywa ważną rolę w niemieckiej historii handlu. Brema słynie z dobrze zachowanego średniowiecznego centrum miasta, muzyków miejskich z Bremy oraz obiektów badawczych związanych z kosmosem. Bremerhaven to znaczący port morski z kompleksem muzeów morskich dokumentujących historię żeglugi w regionie.",
         uk: "Бремен: Цей малий, але історично багатий федеральний штат складається з двох міст, Бремена та Бремерхафену, і відіграє важливу роль у торговельній історії Німеччини. Бремен відомий своїм добре збереженим середньовічним центром міста, музикантами міста Бреми та космічними дослідницькими об'єктами. Бремерхафен є важливим морським портом з комплексом морських музеїв, які документують морську історію регіону.",
         ru: "Бремен: Этот маленький, но исторически богатый федеральный штат состоит из двух городов, Бремена и Бремерхафена, и играет важную роль в торговой истории Германии. Бремен известен своим хорошо сохранившимся средневековым центром города, музыкантами города Бремена и космическими исследовательскими объектами. Бремерхафен - значимый морской порт с комплексом морских музеев, документирующих морскую историю региона.",
         el: "Βρέμη: Αυτό το μικρό αλλά ιστορικά πλούσιο ομόσπονδο κρατίδιο αποτελείται από δύο πόλεις, τη Βρέμη και το Μπρεμερχάφεν, και διαδραματίζει σημαντικό ρόλο στην εμπορική ιστορία της Γερμανίας. Η Βρέμη φημίζεται για το καλά διατηρημένο μεσαιωνικό της κέντρο, τους Μουσικούς της Βρέμης και εγκαταστάσεις διαστημικής έρευνας. Το Μπρεμερχάφεν είναι ένα σημαντικό λιμάνι με ένα ναυτικό μουσείο που καταγράφει τη ναυτική ιστορία της περιοχής.",
         ro: "Bremen: Acest mic, dar bogat din punct de vedere istoric land federal este format din două orașe, Bremen și Bremerhaven, și joacă un rol important în istoria comercială a Germaniei. Bremen este cunoscut pentru centrul său medieval bine conservat, Muzicanții din Bremen și facilitățile de cercetare spațială. Bremerhaven este un port maritim semnificativ, cu un complex muzeal maritim care documentează istoria maritimă a regiunii."
      },
      main_link:
         "https://www.gesundheit.bremen.de/gesundheit/berufe-im-gesundheitswesen/anerkennung-auslaendischer-approbationen-in-heilberufen-37585",
      doctor_palat:"http://www.aekhb.de"
   },
   {
      id: 6,
      name: "Hamburg",
      key: "Hamburg",
      desc: {
         de: "Hamburg: Als reiche Hafenstadt ist Hamburg für seine beeindruckende Architektur, zahlreiche Brücken und Wasserstraßen bekannt. Die Stadt hat eine starke Medien- und Musikindustrie, mit dem historischen Speicherstadtviertel und der neuen Elbphilharmonie als kulturelle Wahrzeichen. Hamburgs Hafen ist einer der größten in Europa und ein zentraler Handelsknotenpunkt.",
         en: "Hamburg: As a wealthy port city, Hamburg is known for its impressive architecture, numerous bridges, and waterways. The city has a strong media and music industry, with the historic Speicherstadt district and the new Elbphilharmonie as cultural landmarks. Hamburg's port is one of the largest in Europe and a central trading hub.",
         fr: "Hambourg : En tant que ville portuaire riche, Hambourg est connue pour son architecture impressionnante, ses nombreux ponts et voies navigables. La ville possède une forte industrie des médias et de la musique, avec le quartier historique de Speicherstadt et la nouvelle Elbphilharmonie comme repères culturels. Le port de Hambourg est l'un des plus grands d'Europe et un carrefour commercial central.",
         es: "Hamburgo: Como ciudad portuaria rica, Hamburgo es conocida por su impresionante arquitectura, numerosos puentes y vías navegables. La ciudad tiene una fuerte industria de medios y música, con el histórico distrito de Speicherstadt y la nueva Elbphilharmonie como puntos de referencia culturales. El puerto de Hamburgo es uno de los más grandes de Europa y un centro de comercio central.",
         ar: "هامبورغ: كمدينة ميناء غنية، تعرف هامبورغ بتصميمها المذهل، والعديد من الجسور والممرات المائية. تتمتع المدينة بصناعة إعلامية وموسيقية قوية، مع حي Speicherstadt التاريخي و Elbphilharmonie الجديد كمعالم ثقافية. ميناء هامبورغ هو واحد من أكبر الموانئ في أوروبا ومركز تجاري مركزي.",
         tr: "Hamburg: Zengin bir liman şehri olarak Hamburg, etkileyici mimarisi, çok sayıda köprüsü ve su yolları ile tanınır. Şehir, tarihi Speicherstadt semti ve yeni Elbphilharmonie kültürel simgeleri ile güçlü bir medya ve müzik endüstrisine sahiptir. Hamburg'un limanı Avrupa'nın en büyüklerinden biridir ve merkezi bir ticaret merkezidir.",
         pl: "Hamburg: Jako bogate miasto portowe Hamburg słynie z imponującej architektury, licznych mostów i dróg wodnych. Miasto posiada silny przemysł medialny i muzyczny, a historyczna dzielnica Speicherstadt i nowa Elbphilharmonie są symbolami kultury. Port w Hamburgu jest jednym z największych w Europie i centralnym węzłem handlowym.",
         uk: "Гамбург: Як багате портове місто, Гамбург відомий своєю вражаючою архітектурою, численними мостами та водними шляхами. Місто має потужну медійну та музичну індустрію, а історичний район Speicherstadt та нова Elbphilharmonie є культурними пам'ятками. Порт Гамбурга є одним з найбільших в Європі та центральним торговим вузлом.",
         ru: "Гамбург: Как богатый портовый город, Гамбург известен своей впечатляющей архитектурой, многочисленными мостами и водными путями. В городе развита сильная медиа- и музыкальная индустрии, с историческим районом Speicherstadt и новой Elbphilharmonie в качестве культурных символов. Порт Гамбурга является одним из крупнейших в Европе и центральным торговым узлом.",
         el: "Αμβούργο: Ως πλούσια λιμενική πόλη, το Αμβούργο φημίζεται για την εντυπωσιακή αρχιτεκτονική του, τις πολυάριθμες γέφυρες και τους υδάτινους δρόμους. Η πόλη διαθέτει μια ισχυρή βιομηχανία μέσων ενημέρωσης και μουσικής, με τη θρυλική Speicherstadt και τη νέα Elbphilharmonie ως πολιτιστικά ορόσημα. Το λιμάνι του Αμβούργου είναι ένα από τα μεγαλύτερα στην Ευρώπη και ένας κεντρικός εμπορικός κόμβος.",
         ro: "Hamburg: Ca un oraș portuar bogat, Hamburg este cunoscut pentru arhitectura sa impresionantă, numeroasele poduri și canale de apă. Orașul are o industrie media și muzicală puternică, cu districtul istoric Speicherstadt și noua Elbphilharmonie drept repere culturale. Portul din Hamburg este unul dintre cele mai mari din Europa și un important nod comercial."
      },
      main_link: "https://www.hamburg.de/behoerdenfinder/info/11966145/n0/",
      doctor_palat:"http://www.aerztekammer-hamburg.org"
   },
   {
      id: 7,
      name: "Hessen",
      key: "Hessen",
      desc: {
         de: "Hessen: Im Herzen Deutschlands gelegen, vereint Hessen historische Städte wie die Römerstadt Mainz mit dem modernen Finanzzentrum Frankfurt am Main. Frankfurt, die größte Stadt Hessens, ist ein globales Finanzzentrum mit einer beeindruckenden Skyline und dient als wichtiger Verkehrsknotenpunkt in Europa. Hessen ist außerdem für seine vielfältige Natur bekannt, von niedrigen Mittelgebirgen bis hin zu Flusslandschaften.",
         en: "Hessen: Located in the heart of Germany, Hessen combines historical cities like the Roman city of Mainz with the modern financial center of Frankfurt am Main. Frankfurt, the largest city in Hessen, is a global financial hub with an impressive skyline and serves as a key transportation hub in Europe. Hessen is also known for its diverse nature, from the low mountain ranges to the river landscapes.",
         fr: "Hesse : Située au cœur de l'Allemagne, la Hesse combine des villes historiques comme la cité romaine de Mayence avec le centre financier moderne de Francfort-sur-le-Main. Francfort, la plus grande ville de Hesse, est un centre financier mondial avec une skyline impressionnante et sert de plaque tournante des transports en Europe. La Hesse est également connue pour sa nature diversifiée, des montagnes basses aux paysages fluviaux.",
         es: "Hesse: Situada en el corazón de Alemania, Hesse combina ciudades históricas como la ciudad romana de Maguncia con el moderno centro financiero de Fráncfort del Meno. Fráncfort, la ciudad más grande de Hesse, es un centro financiero global con un impresionante horizonte y sirve como un importante centro de transporte en Europa. Hesse también es conocida por su naturaleza diversa, desde las cordilleras bajas hasta los paisajes fluviales.",
         ar: "هيسن: تقع في قلب ألمانيا، تجمع هيسن بين المدن التاريخية مثل مدينة ماينز الرومانية مع المركز المالي الحديث في فرانكفورت آم ماين. فرانكفورت، أكبر مدينة في هيسن، هي مركز مالي عالمي بأفق مذهل وتعتبر مركزاً رئيسياً للنقل في أوروبا. تشتهر هيسن أيضاً بتنوع طبيعتها، من سلاسل الجبال المنخفضة إلى المناظر الطبيعية النهرية.",
         tr: "Hessen: Almanya'nın kalbinde bulunan Hessen, Roma şehri Mainz gibi tarihi şehirleri modern Frankfurt am Main finans merkeziyle birleştirir. Hessen'in en büyük şehri olan Frankfurt, etkileyici bir silueti olan küresel bir finans merkezi ve Avrupa'daki ana ulaşım merkezlerinden biri olarak hizmet vermektedir. Hessen, alçak dağ sıralarından nehir manzaralarına kadar çeşitli doğası ile de tanınır.",
         pl: "Hesja: Położona w sercu Niemiec Hesja łączy historyczne miasta jak rzymskie miasto Moguncja z nowoczesnym centrum finansowym Frankfurt nad Menem. Frankfurt, największe miasto Hesji, to globalne centrum finansowe z imponującą linią horyzontu i pełni rolę kluczowego węzła transportowego w Europie. Hesja znana jest także ze swojej różnorodnej przyrody, od niskich pasm górskich po krajobrazy rzeczne.",
         uk: "Гессен: Знаходиться в серці Німеччини, Гессен поєднує в собі історичні міста, такі як римське місто Майнц з сучасним фінансовим центром Франкфурт-на-Майні. Франкфурт, найбільше місто Гессена, є глобальним фінансовим центром з вражаючою лінією горизонту і є ключовим транспортним вузлом в Європі. Гессен також відомий своєю різноманітною природою, від низьких гірських хребтів до річкових пейзажів.",
         ru: "Гессен: Расположенная в сердце Германии, Гессен сочетает в себе исторические города, такие как римский город Майнц, с современным финансовым центром Франкфурт-на-Майне. Франкфурт, самый крупный город Гессена, является глобальным финансовым центром с впечатляющим городским силуэтом и служит ключевым транспортным узлом в Европе. Гессен также известен своим разнообразием природы, от низких горных хребтов до речных пейзажей.",
         el: "Έσση: Βρίσκεται στην καρδιά της Γερμανίας και συνδυάζει ιστορικές πόλεις όπως τη ρωμαϊκή πόλη Μάιντς με το σύγχρονο χρηματοπιστωτικό κέντρο της Φρανκφούρτης. Η Φρανκφούρτη, η μεγαλύτερη πόλη της Έσσης, είναι ένα παγκόσμιο οικονομικό κέντρο με εντυπωσιακή αστική γραμμή και αποτελεί βασικό συγκοινωνιακό κόμβο στην Ευρώπη. Επιπλέον, η Έσση είναι γνωστή για τη φυσική της ποικιλία, από χαμηλές οροσειρές έως ποτάμιες κοιλάδες.",
         ro: "Hessen: Situat în inima Germaniei, landul Hessen combină orașe istorice precum cel roman Mainz cu centrul financiar modern Frankfurt pe Main. Frankfurt, cel mai mare oraș din Hessen, este un hub financiar global cu o linie impresionantă a orizontului și servește drept un important nod de transport în Europa. Hessen este cunoscut și pentru natura sa diversă, de la lanțuri montane joase până la peisaje fluviale."
      },
      main_link:
         "https://verwaltungsportal.hessen.de/leistung?leistung_id=L100001_8958940",
      doctor_palat:"http://www.laekh.de"
   },
   {
      id: 8,
      name: "Mecklenburg Vorpommern",
      key: "MecklenburgVorpommern",
      desc: {
         de: "Mecklenburg-Vorpommern: Bekannt für seine malerische Ostseeküste mit langen Sandstränden, Inseln wie Rügen und Usedom und die Mecklenburgische Seenplatte. Dieses Bundesland zieht Naturliebhaber und Wassersportler an. Die historischen Hansestädte Rostock und Stralsund bieten reiche Kulturerlebnisse und maritime Geschichte.",
         en: "Mecklenburg-Vorpommern: Known for its picturesque Baltic Sea coast with long sandy beaches, islands like Rügen and Usedom, and the Mecklenburg Lake District. This state attracts nature lovers and water sports enthusiasts. The historic Hanseatic cities of Rostock and Stralsund offer rich cultural experiences and maritime history.",
         fr: "Mecklembourg-Poméranie occidentale : Connu pour sa pittoresque côte de la mer Baltique avec de longues plages de sable, des îles comme Rügen et Usedom, et le district des lacs de Mecklembourg. Cet État attire les amoureux de la nature et les passionnés de sports nautiques. Les villes hanséatiques historiques de Rostock et de Stralsund offrent des expériences culturelles riches et une histoire maritime.",
         es: "Mecklemburgo-Pomerania Occidental: Conocido por su pintoresca costa del mar Báltico con largas playas de arena, islas como Rügen y Usedom, y el distrito de los lagos de Mecklemburgo. Este estado atrae a amantes de la naturaleza y entusiastas de los deportes acuáticos. Las históricas ciudades hanseáticas de Rostock y Stralsund ofrecen ricas experiencias culturales e historia marítima.",
         ar: "ميكلنبورغ-فوربومرن: معروفة بساحلها البحري الخلّاب على بحر البلطيق بشواطئ رملية طويلة، وجزر مثل روغن وأوسيدوم، ومنطقة البحيرات في ميكلنبورغ. يجذب هذا الولاية عشاق الطبيعة وهواة الرياضات المائية. تقدم المدن التاريخية الهانزية روستوك وشترالسوند تجارب ثقافية غنية وتاريخًا بحريًا.",
         tr: "Mecklenburg-Vorpommern: Uzun kumsallı Baltık Denizi kıyıları, Rügen ve Usedom gibi adaları ve Mecklenburg Göl Bölgesi ile tanınır. Bu eyalet, doğa severleri ve su sporları meraklılarını kendine çeker. Tarihi Hansa şehirleri Rostock ve Stralsund zengin kültürel deneyimler ve denizcilik tarihi sunar.",
         pl: "Meklemburgia-Pomorze Przednie: Znane z malowniczej wybrzeża Bałtyku z długimi plażami, wyspami takimi jak Rugia i Uznam oraz Pojezierzem Meklemburskim. Ten stan przyciąga miłośników natury i entuzjastów sportów wodnych. Historyczne miasta hanzeatyckie Rostock i Stralsund oferują bogate doświadczenia kulturowe i historię morską.",
         uk: "Мекленбург-Передня Померанія: Відома своїм мальовничим узбережжям Балтійського моря з довгими піщаними пляжами, островами Рюген і Узедом, а також Мекленбурзьким озерним краєм. Ця земля приваблює любителів природи та водних видів спорту. Історичні ганзейські міста Росток і Штральзунд пропонують багатий культурний досвід і морську історію.",
         ru: "Мекленбург-Передняя Померания: Известна своим живописным побережьем Балтийского моря с длинными песчаными пляжами, островами Рюген и Узедом, а также Мекленбургским озерным краем. Этот федеральный штат привлекает любителей природы и водных видов спорта. Исторические ганзейские города Росток и Штральзунд предлагают богатые культурные впечатления и морскую историю.",
         el: "Το Μεκλεμβούργο-Προπομερανία: Γνωστό για την ειδυλλιακή ακτή της Βαλτικής με μεγάλες αμμώδεις παραλίες, νησιά όπως το Rügen και το Usedom, καθώς και την περιοχή λιμνών του Μεκλεμβούργου. Αυτό το κρατίδιο προσελκύει τους λάτρεις της φύσης και των θαλάσσιων σπορ. Οι ιστορικές Χανσεατικές πόλεις Ρόστοκ και Στράλσουντ προσφέρουν πλούσιες πολιτιστικές εμπειρίες και ναυτική ιστορία.",
         ro: "Mecklenburg-Pomerania Anterioară: Cunoscută pentru coasta sa pitorească la Marea Baltică, cu plaje lungi de nisip, insule precum Rügen și Usedom, precum și zona de lacuri din Mecklenburg. Acest land atrage iubitorii de natură și pasionații de sporturi nautice. Orașele hanseatice istorice Rostock și Stralsund oferă experiențe culturale bogate și istorie maritimă."
      },
      main_link: "https://www.lagus.mv-regierung.de/LPH/Approbationsberufe/",
      doctor_palat: "http://www.aek-mv.de"
   },
   {
      id: 9,
      name: "Niedersachsen",
      key: "Niedersachsen",
      desc: {
         de: "Nordrhein-Westfalen: Das bevölkerungsreichste Bundesland und ein industrieller Schmelztiegel mit Städten wie Köln, Düsseldorf und dem Ruhrgebiet. Diese Region ist bekannt für ihre Industriekultur, moderne Kunst und lebhafte Festivals. Nordrhein-Westfalen hat eine starke Wirtschaft, unterstützt durch eine hohe Dichte an Universitäten und Forschungseinrichtungen.",
         en: "Niedersachsen: With a mix of large cities like Hannover and idyllic landscapes like the Harz Mountains and the North Sea, Niedersachsen offers a variety of habitats. Agriculture, especially in the Lüneburg Heath, plays a significant role in the state's economy, as does the automotive industry with Volkswagen in Wolfsburg.",
         fr: "Basse-Saxe : Avec un mélange de grandes villes comme Hanovre et de paysages idylliques comme les montagnes du Harz et la mer du Nord, la Basse-Saxe offre une variété d'habitats. L'agriculture, notamment dans la lande de Lunebourg, joue un rôle important dans l'économie de l'État, tout comme l'industrie automobile avec Volkswagen à Wolfsburg.",
         es: "Baja Sajonia: Con una mezcla de grandes ciudades como Hannover y paisajes idílicos como las montañas del Harz y el Mar del Norte, Baja Sajonia ofrece una variedad de hábitats. La agricultura, especialmente en el brezal de Lüneburg, desempeña un papel significativo en la economía del estado, al igual que la industria automotriz con Volkswagen en Wolfsburg.",
         ar: "نيدرساكسن: مع مزيج من المدن الكبيرة مثل هانوفر والمناظر الطبيعية الخلابة مثل جبال هارتس وبحر الشمال، تقدم نيدرساكسن مجموعة متنوعة من المواطن. الزراعة، خاصة في لونبورغ هيث، تلعب دوراً هاماً في اقتصاد الولاية، وكذلك صناعة السيارات مع فولكس واجن في فولفسبورغ.",
         tr: "Aşağı Saksonya: Hannover gibi büyük şehirlerle ve Harz Dağları ve Kuzey Denizi gibi doğal güzelliklerle karışık bir yapıya sahip olan Aşağı Saksonya, çeşitli yaşam alanları sunar. Özellikle Lüneburg Heath'te tarım, eyalet ekonomisinde önemli bir rol oynar. Wolfsburg'daki Volkswagen gibi otomotiv endüstrisi de ayrıca önemlidir.",
         pl: "Dolna Saksonia: Z mieszanką dużych miast, takich jak Hanower, i sielankowych krajobrazów, takich jak Góry Harzu i Morze Północne, Dolna Saksonia oferuje różnorodne siedliska. Rolnictwo, zwłaszcza w Lüneburg Heath, odgrywa istotną rolę w gospodarce stanu, podobnie jak przemysł motoryzacyjny z Volkswagenem w Wolfsburgu.",
         uk: "Нижня Саксонія: З поєднанням великих міст, таких як Ганновер, та ідилічних пейзажів, як-от гори Гарц і Північне море, Нижня Саксонія пропонує різноманітні середовища існування. Сільське господарство, особливо в Люнебурзькій пустці, відіграє значну роль в економіці землі, як і автомобільна промисловість з компанією Volkswagen у Вольфсбурзі.",
         ru: "Нижняя Саксония: Сочетает в себе крупные города, такие как Ганновер, и идиллические ландшафты, такие как горы Гарц и Северное море, предлагая разнообразные места обитания. Сельское хозяйство, особенно в Люнебургской пустоши, играет значительную роль в экономике земли, как и автомобильная промышленность с Volkswagen в Вольфсбурге.",
         el: "Κάτω Σαξονία: Με ένα μείγμα μεγαλουπόλεων όπως το Ανόβερο και ειδυλλιακών τοπίων όπως τα βουνά Harz και η Βόρεια Θάλασσα, η Κάτω Σαξονία προσφέρει μια ποικιλία βιοτόπων. Η γεωργία, ιδίως στη λεκάνη Lüneburg, παίζει σημαντικό ρόλο στην οικονομία του κρατιδίου, όπως και η αυτοκινητοβιομηχανία με τη Volkswagen στο Βόλφσμπουργκ.",
         ro: "Saxonia Inferioară: Cu un amestec de orașe mari precum Hanovra și peisaje idilice precum Munții Harz și Marea Nordului, Saxonia Inferioară oferă o varietate de habitate. Agricultura, în special în zona Lüneburg Heath, joacă un rol semnificativ în economia landului, la fel ca industria auto, reprezentată de Volkswagen în Wolfsburg."
      },
      main_link:
         "https://www.nizza.niedersachsen.de/startseite/abteilung_1_approbationen_und_berufserlaubnisse_anerkennung_auslaendischer_berufsqualifikationen/approbationen-und-berufserlaubnisse-anerkennung-auslaendischer-berufsqualifikationen-150219.html",
      doctor_palat:"http://www.aekn.de"
   },
   {
      id: 10,
      name: "Nordrhein-Westfalen",
      key: "NordrheinWestfalen",
      desc: {
         en: "Nordrhein-Westfalen: The most populous federal state and an industrial melting pot with cities like Cologne, Düsseldorf, and the Ruhr area. This region is known for its industrial culture, modern art, and vibrant festivals. Nordrhein-Westfalen has a strong economy, supported by a high density of universities and research institutions.",
         fr: "Rhénanie-du-Nord-Westphalie : Le Land le plus peuplé et un creuset industriel avec des villes comme Cologne, Düsseldorf et la région de la Ruhr. Cette région est connue pour sa culture industrielle, son art moderne et ses festivals animés. La Rhénanie-du-Nord-Westphalie dispose d'une économie forte, soutenue par une forte densité d'universités et d'institutions de recherche.",
         es: "Renania del Norte-Westfalia: El estado federal más poblado y un crisol industrial con ciudades como Colonia, Düsseldorf y la cuenca del Ruhr. Esta región es conocida por su cultura industrial, arte moderno y festivales vibrantes. Renania del Norte-Westfalia tiene una economía fuerte, apoyada por una alta densidad de universidades e instituciones de investigación.",
         ar: "شمال الراين - وستفاليا: الولاية الفيدرالية الأكثر اكتظاظا بالسكان ومنطقة مزج صناعي مع مدن مثل كولونيا ودوسلدورف ومنطقة الروار. تشتهر هذه المنطقة بثقافتها الصناعية والفن الحديث والمهرجانات النابضة بالحياة. تتمتع شمال الراين - وستفاليا باقتصاد قوي، مدعومًا بكثافة عالية من الجامعات والمؤسسات البحثية.",
         tr: "Kuzey Ren-Vestfalya: En kalabalık federal eyalet ve sanayi alanında Köln, Düsseldorf ve Ruhr bölgesi gibi şehirlere sahip bir eriyik kazanı. Bu bölge, endüstriyel kültürü, modern sanatı ve canlı festivalleri ile tanınır. Kuzey Ren-Vestfalya, yüksek üniversite ve araştırma kurumu yoğunluğu ile desteklenen güçlü bir ekonomiye sahiptir.",
         pl: "Nadrenia Północna-Westfalia: Najludniejszy kraj związkowy i przemysłowy tygiel z takimi miastami jak Kolonia, Düsseldorf i Zagłębie Ruhry. Region znany jest z kultury przemysłowej, sztuki nowoczesnej i tętniących życiem festiwali. Nadrenia Północna-Westfalia posiada silną gospodarkę, wspieraną przez wysokie zagęszczenie uniwersytetów i instytucji badawczych.",
         uk: "Північний Рейн-Вестфалія: Найнаселеніший федеральний штат та промисловий центр з містами, такими як Кельн, Дюссельдорф і регіон Рура. Цей регіон відомий промисловою культурою, сучасним мистецтвом і яскравими фестивалями. Північний Рейн-Вестфалія має потужну економіку, підтриману високою щільністю університетів і науково-дослідних установ.",
         ru: "Северный Рейн-Вестфалия: Самый населенный федеральный штат и промышленный котел с городами, такими как Кёльн, Дюссельдорф и Рурская область. Этот регион известен своей промышленной культурой, современным искусством и яркими фестивалями. У Северного Рейна-Вестфалии сильная экономика, поддержанная высокой плотностью университетов и научно-исследовательских учреждений.",
         de: "Nordrhein-Westfalen: Das bevölkerungsreichste Bundesland und ein industrieller Schmelztiegel mit Städten wie Köln, Düsseldorf und dem Ruhrgebiet. Diese Region ist bekannt für ihre Industriekultur, moderne Kunst und lebhafte Festivals. Nordrhein-Westfalen hat eine starke Wirtschaft, unterstützt durch eine hohe Dichte an Universitäten und Forschungseinrichtungen.",
         el: "Βόρεια Ρηνανία-Βεστφαλία: Το πιο πολυπληθές ομόσπονδο κρατίδιο και ένα βιομηχανικό σημείο τήξης με πόλεις όπως η Κολωνία, το Ντίσελντορφ και η περιοχή του Ρουρ. Αυτή η περιοχή είναι γνωστή για τον βιομηχανικό πολιτισμό, τη σύγχρονη τέχνη και τα ζωντανά φεστιβάλ της. Η Βόρεια Ρηνανία-Βεστφαλία διαθέτει ισχυρή οικονομία, υποστηριζόμενη από την υψηλή πυκνότητα πανεπιστημίων και ερευνητικών ιδρυμάτων.",
         ro: "Renania de Nord-Westfalia: Cel mai populat land federal și un creuzet industrial cu orașe precum Köln, Düsseldorf și zona Ruhr. Această regiune este cunoscută pentru cultura sa industrială, arta modernă și festivalurile vibrante. Renania de Nord-Westfalia are o economie puternică, susținută de o densitate mare de universități și instituții de cercetare."
      },
      main_link:
         "https://www.bezreg-muenster.de/de/gesundheit_und_soziales/zag/approbation_nrw/muenster/arzt/index.html",
      doctor_palat:"http://www.aekwl.de"
   },
   {
      id: 11,
      name: "Rheinland-Pfalz",
      key: "RheinlandPfalz",
      desc: {
         en: "Rheinland-Pfalz: This federal state is known for its picturesque wine-growing regions along the Rhine and Moselle rivers, as well as historical cities like Trier and Mainz. Rheinland-Pfalz is rich in culture and history, with many castles, palaces, and Roman monuments.",
         fr: "Rheinland-Pfalz : Cet État fédéral est connu pour ses pittoresques régions viticoles le long du Rhin et de la Moselle, ainsi que pour des villes historiques comme Trèves et Mayence. Rheinland-Pfalz est riche en culture et en histoire, avec de nombreux châteaux, palais et monuments romains.",
         es: "Renania-Palatinado: Este estado federal es conocido por sus pintorescas regiones vitivinícolas a lo largo de los ríos Rin y Mosela, así como por ciudades históricas como Tréveris y Maguncia. Renania-Palatinado es rico en cultura e historia, con muchos castillos, palacios y monumentos romanos.",
         ar: "راينلاند بالاتينات: تشتهر هذه الولاية الفيدرالية بمناطق زراعة النبيذ الخلابة على طول نهري الراين والموزيل، وكذلك بالمدن التاريخية مثل ترير وماينتس. راينلاند بالاتينات غنية بالثقافة والتاريخ، مع العديد من القلاع والقصور والآثار الرومانية.",
         tr: "Rheinland-Pfalz: Bu eyalet, Ren ve Moselle nehirleri boyunca uzanan resim gibi bağcılık bölgeleri ve Trier ve Mainz gibi tarihi şehirleriyle tanınır. Rheinland-Pfalz, çok sayıda kale, saray ve Roma anıtıyla zengin bir kültüre ve tarihe sahiptir.",
         pl: "Rheinland-Pfalz: Ten kraj związkowy jest znany z malowniczych regionów winiarskich wzdłuż rzek Renu i Mozeli, a także z historycznych miast, takich jak Trewir i Moguncja. Rheinland-Pfalz jest bogaty w kulturę i historię, posiadając wiele zamków, pałaców i zabytków rzymskich.",
         uk: "Рейнланд-Пфальц: Цей федеральний штат відомий своїми мальовничими виноробними регіонами вздовж річок Рейн і Мозель, а також історичними містами, такими як Трір і Майнц. Рейнланд-Пфальц багатий на культуру і історію, з безліччю замків, палаців і римських пам'яток.",
         ru: "Рейнланд-Пфальц: Этот федеральный штат известен своими живописными винодельческими регионами вдоль рек Рейн и Мозель, а также историческими городами, такими как Трир и Майнц. Рейнланд-Пфальц богат культурой и историей, здесь много замков, дворцов и римских памятников.",
         de: "Rheinland-Pfalz: Dieses Bundesland ist bekannt für seine malerischen Weinanbaugebiete entlang des Rheins und der Mosel sowie für historische Städte wie Trier und Mainz. Rheinland-Pfalz ist reich an Kultur und Geschichte, mit vielen Burgen, Schlössern und römischen Denkmälern.",
         el: "Ρηνανία-Παλατινάτο: Αυτό το ομόσπονδο κρατίδιο είναι γνωστό για τις γραφικές αμπελουργικές περιοχές του κατά μήκος του Ρήνου και του Μοζέλα, καθώς και για ιστορικές πόλεις όπως η Τρηρ και η Μάιντς. Η Ρηνανία-Παλατινάτο είναι πλούσια σε πολιτισμό και ιστορία, με πολυάριθμα κάστρα, παλάτια και ρωμαϊκά μνημεία.",
         ro: "Renania-Palatinat: Acest land este cunoscut pentru regiunile sale pitorești de viticultură de-a lungul râurilor Rin și Mosela, precum și pentru orașe istorice precum Trier și Mainz. Renania-Palatinat are o cultură și o istorie bogată, cu numeroase castele, palate și monumente romane."
      },
      main_link:
         "https://lsjv.rlp.de/de/unsere-aufgaben/arbeit/akademische-heilberufe/approbationen-und-berufserlaubnisse/",
      doctor_palat: "http://www.laek-rlp.de" 
   },
   {
      id: 12,
      name: "Saarland",
      key: "Saarland",
      desc: {
         en: "Saarland: Shaped by its industrial history and proximity to France, Saarland offers a unique blend of German and French culture. The region is known for its steel industry and culinary specialties, including the Saarland Lyoner.",
         fr: "Sarre : Façonné par son histoire industrielle et sa proximité avec la France, le Sarre offre un mélange unique de culture allemande et française. La région est connue pour son industrie sidérurgique et ses spécialités culinaires, notamment le Lyoner sarrois.",
         es: "Saarland: Moldeado por su historia industrial y su proximidad a Francia, el Sarre ofrece una combinación única de cultura alemana y francesa. La región es conocida por su industria del acero y especialidades culinarias, incluido el Lyoner de Sarre.",
         ar: "سارلاند: تشكل من تاريخها الصناعي وقربها من فرنسا، تقدم سارلاند مزيجًا فريدًا من الثقافة الألمانية والفرنسية. تشتهر المنطقة بصناعتها الصلب والتخصصات الغذائية، بما في ذلك الليونير سارلاند.",
         tr: "Saarland: Endüstriyel tarihinden etkilenen ve Fransa'ya yakınlığı ile şekillenen Saarland, Alman ve Fransız kültürünün benzersiz bir karışımını sunar. Bölge, çelik endüstrisi ve Saarland Lyoner'i de içeren yemek özelikleriyle tanınır.",
         pl: "Saara: Ukształtowane przez swoją historię przemysłową i bliskość Francji, Saara oferuje unikalne połączenie niemieckiej i francuskiej kultury. Region znany jest z przemysłu stalowego i specjałów kulinarnych, w tym Saara Lyoner.",
         uk: "Земля Заар: Сформована своєю промисловою історією та близькістю до Франції, Земля Заар пропонує унікальне поєднання німецької та французької культури. Регіон відомий своєю сталевою промисловістю та кулінарними спеціальностями, зокрема Заарський Ліонер.",
         ru: "Саарланд: Оформленный своей промышленной историей и близостью к Франции, Саарланд предлагает уникальное сочетание немецкой и французской культуры. Регион известен своей стальной промышленностью и кулинарными специальностями, включая саарландский Лионер.",
         de: "Saarland: Geprägt von seiner Industriegeschichte und der Nähe zu Frankreich, bietet das Saarland eine einzigartige Mischung aus deutscher und französischer Kultur. Die Region ist bekannt für ihre Stahlindustrie und kulinarischen Spezialitäten, einschließlich des Saarländer Lyoners.",
         el: "Σάαρλαντ: Διαμορφωμένο από την βιομηχανική του ιστορία και την εγγύτητα στη Γαλλία, το Σάαρλαντ προσφέρει έναν μοναδικό συνδυασμό γερμανικού και γαλλικού πολιτισμού. Η περιοχή είναι γνωστή για τη χαλυβουργία της και τις γαστρονομικές σπεσιαλιτέ, συμπεριλαμβανομένου του Saarland Lyoner.",
         ro: "Saarland: Marcat de istoria sa industrială și de apropierea de Franța, Saarland oferă un amestec unic de cultură germană și franceză. Regiunea este cunoscută pentru industria sa siderurgică și specialitățile culinare, inclusiv Saarland Lyoner."
      },
      main_link:
         "https://www.saarland.de/las/DE/themen/gesundheitsberufe/approbation/approbation_node.html",
      doctor_palat: "http://www.aerztekammer-saarland.de"
   },
   {
      id: 13,
      name: "Sachsen",
      key: "Sachsen",
      desc: {
         en: "Saxony: With a strong cultural identity expressed in cities like Dresden and Leipzig with their rich art and music history, Saxony has a thriving creative industry and is known for its traditional Christmas markets and the Ore Mountains.",
         fr: "Saxe : Avec une forte identité culturelle exprimée dans des villes comme Dresde et Leipzig avec leur riche histoire de l'art et de la musique, la Saxe a une industrie créative florissante et est connue pour ses marchés de Noël traditionnels et les monts Métallifères.",
         es: "Sajonia: Con una fuerte identidad cultural expresada en ciudades como Dresde y Leipzig con su rica historia artística y musical, Sajonia tiene una próspera industria creativa y es conocida por sus tradicionales mercados navideños y las montañas de Erzgebirge.",
         ar: "ساكسونيا: بمعرفة هوية ثقافية قوية تعبِّر عنها مدن مثل درسدن وليبزيغ مع تاريخها الفني والموسيقي الغني، تتمتع ساكسونيا بصناعة إبداعية مزدهرة ومعروفة بأسواقها التقليدية لعيد الميلاد وجبال أوري.",
         tr: "Saksonya: Dresden ve Leipzig gibi şehirlerde ifade edilen güçlü bir kültürel kimliğe sahip olan Saksonya, gelişen bir yaratıcı endüstriye sahiptir ve geleneksel Noel pazarları ile Erzgebirge Dağları ile tanınır.",
         pl: "Saksonia: Z silną tożsamością kulturową wyrażaną w miastach takich jak Drezno i Lipsk, mających bogatą historię sztuki i muzyki, Saksonia ma rozwijający się przemysł kreatywny i jest znana z tradycyjnych jarmarków bożonarodzeniowych oraz Rudaw.",
         uk: "Саксонія: Маючи потужну культурну ідентичність, виражену в містах Дрезден і Лейпциг з їх багатою історією мистецтва та музики, Саксонія має процвітаючу творчу індустрію і відома своїми традиційними різдвяними ярмарками та Рудними горами.",
         ru: "Саксония: Обладает сильной культурной идентичностью, выраженной в таких городах, как Дрезден и Лейпциг, с их богатой историей искусства и музыки. Саксония имеет процветающую креативную индустрию и известна своими традиционными рождественскими ярмарками и Рудными горами.",
         de: "Sachsen: Mit einer starken kulturellen Identität, die in Städten wie Dresden und Leipzig mit ihrer reichen Kunst- und Musikgeschichte zum Ausdruck kommt, hat Sachsen eine blühende Kreativwirtschaft und ist bekannt für seine traditionsreichen Weihnachtsmärkte und das Erzgebirge.",
         el: "Σαξονία: Με ισχυρή πολιτιστική ταυτότητα που εκφράζεται σε πόλεις όπως η Δρέσδη και η Λειψία, οι οποίες διαθέτουν πλούσια ιστορία τέχνης και μουσικής, η Σαξονία διαθέτει μια ακμάζουσα δημιουργική βιομηχανία και είναι γνωστή για τις παραδοσιακές χριστουγεννιάτικες αγορές της και τα Όρη Έρτσγκεμπιργκε.",
         ro: "Saxonia: Cu o identitate culturală puternică exprimată în orașe precum Dresda și Leipzig, care au o istorie bogată în artă și muzică, Saxonia are o industrie creativă înfloritoare și este cunoscută pentru târgurile sale tradiționale de Crăciun și Munții Metaliferi (Erzgebirge)."
      },
      main_link: "https://www.lds.sachsen.de/soziales/index.asp?art_param=684",
      doctor_palat: "http://www.slaek.de"
   },
   {
      id: 14,
      name: "Sachsen-Anhalt",
      key: "SachsenAnhalt",
      desc: {
         en: "Sachsen-Anhalt: Known for its UNESCO World Heritage sites such as Lutherstadt Wittenberg and the Naumburger Dom. This federal state offers a rich historical landscape ranging from prehistory to the Reformation and is a center for the chemical industry.",
         fr: "Saxe-Anhalt : Connu pour ses sites du patrimoine mondial de l'UNESCO comme la Lutherstadt Wittenberg et le Naumburger Dom. Cet État fédéral offre un paysage historique riche allant de la préhistoire à la Réforme et est un centre pour l'industrie chimique.",
         es: "Sajonia-Anhalt: Conocido por sus sitios del Patrimonio Mundial de la UNESCO como Lutherstadt Wittenberg y el Naumburger Dom. Este estado federal ofrece un rico paisaje histórico que abarca desde la prehistoria hasta la Reforma y es un centro para la industria química.",
         ar: "ساكسونيا أنهالت: معروفة بمواقعها في التراث العالمي لليونسكو مثل لوثرشتادت فيتنبرغ وكاتدرائية ناومبورغ. يقدم هذا الولاية الفدرالية مناظر تاريخية غنية تمتد من عصور ما قبل التاريخ إلى الإصلاح وهو مركز لصناعة الكيماويات.",
         tr: "Sachsen-Anhalt: Lutherstadt Wittenberg ve Naumburger Dom gibi UNESCO Dünya Mirası alanlarıyla bilinir. Bu eyalet, tarih öncesi dönemden Reform'a uzanan zengin bir tarihi manzara sunar ve kimya endüstrisinin merkezlerinden biridir.",
         pl: "Saksonia-Anhalt: Znane z miejsc światowego dziedzictwa UNESCO, takich jak Lutherstadt Wittenberg i Naumburger Dom. Ten kraj związkowy oferuje bogaty krajobraz historyczny, rozciągający się od prehistorii po Reformację, i jest ośrodkiem przemysłu chemicznego.",
         uk: "Саксонія-Ангальт: Відома своїми об'єктами світової спадщини ЮНЕСКО, такими як Лютерштадт Віттенберг та Наумбурзький собор. Ця федеральна земля пропонує багатий історичний ландшафт від доісторичних часів до Реформації та є центром хімічної промисловості.",
         ru: "Саксония-Ангальт: Известна своими объектами Всемирного наследия ЮНЕСКО, такими как Лютерштадт Виттенберг и Наумбургский собор. Эта федеральная земля предлагает богатый исторический ландшафт, охватывающий период от доисторических времен до Реформации, и является центром химической промышленности.",
         de: "Sachsen-Anhalt: Bekannt für seine UNESCO-Welterbestätten wie die Lutherstadt Wittenberg und den Naumburger Dom. Dieses Bundesland bietet eine reiche historische Landschaft, die von der Frühgeschichte bis zur Reformation reicht, und ist ein Zentrum für chemische Industrie.",
         el: "Σαξονία-Άνχαλτ: Γνωστή για τα μνημεία παγκόσμιας κληρονομιάς της UNESCO, όπως η Λουθηροπόλη Βιτεμβέργη (Lutherstadt Wittenberg) και ο Καθεδρικός του Ναούμπουργκ. Αυτό το ομόσπονδο κρατίδιο προσφέρει ένα πλούσιο ιστορικό τοπίο, που εκτείνεται από την προϊστορία έως τη Μεταρρύθμιση και αποτελεί κέντρο της χημικής βιομηχανίας.",
         ro: "Saxonia-Anhalt: Cunoscută pentru siturile sale din Patrimoniul Mondial UNESCO, precum Lutherstadt Wittenberg și Domul din Naumburg. Acest land oferă un peisaj istoric bogat, de la preistorie până la Reforma protestantă, și este un centru pentru industria chimică."
      },
      main_link:
         "https://lvwa.sachsen-anhalt.de/das-lvwa/landespruefungsamt-fuer-gesundheitsberufe/akademische-gesundheitsberufe/studium-im-ausland-berufserlaubnisse-und-approbationen",
      doctor_palat: "http://www.aeksa.de"
   },
   {
      id: 15,
      name: "Schleswig-Holstein",
      key: "SchleswigHolstein",
      desc: {
         en: "Schleswig-Holstein: Located between the North Sea and the Baltic Sea, it offers a unique maritime culture, with important port cities such as Kiel and Lübeck. The region is known for its sailing events, the Wacken Open Air music festival, and the Holstein lake district.",
         fr: "Schleswig-Holstein : Situé entre la mer du Nord et la mer Baltique, il offre une culture maritime unique, avec des villes portuaires importantes telles que Kiel et Lübeck. La région est connue pour ses événements de voile, le festival de musique Wacken Open Air et le district des lacs de Holstein.",
         es: "Schleswig-Holstein: Ubicado entre el Mar del Norte y el Mar Báltico, ofrece una cultura marítima única, con importantes ciudades portuarias como Kiel y Lübeck. La región es conocida por sus eventos de navegación, el festival de música Wacken Open Air y el distrito de lagos de Holstein.",
         ar: "شليسفيغ هولشتاين: تقع بين بحر الشمال وبحر البلطيق، وتقدم ثقافة بحرية فريدة، مع مدن ميناء مهمة مثل كيل ولوبيك. تشتهر المنطقة بأحداث الإبحار الخاصة بها، ومهرجان موسيقى واكن أوبن إير، ومنطقة بحيرات هولشتاين.",
         tr: "Schleswig-Holstein: Kuzey Denizi ve Baltık Denizi arasında yer alır ve Kiel ve Lübeck gibi önemli liman şehirleri ile benzersiz bir deniz kültürü sunar. Bölge, yelken etkinlikleri, Wacken Açık Hava Müzik Festivali ve Holstein göl bölgesi ile tanınır.",
         pl: "Szlezwik-Holsztyn: Położony między Morzem Północnym a Bałtyckim, oferuje unikalną kulturę morską, z ważnymi miastami portowymi, takimi jak Kilonia i Lubeka. Region znany jest z imprez żeglarskich, festiwalu muzyki Wacken Open Air i okręgu jezior Holstein.",
         uk: "Шлезвіг-Гольштейн: Розташований між Північним морем і Балтійським морем, він пропонує унікальну морську культуру з важливими портовими містами, такими як Кіль і Любек. Регіон відомий своїми вітрильними заходами, музичним фестивалем Wacken Open Air та Гольштейнським озерним районом.",
         ru: "Шлезвиг-Гольштейн: Расположенный между Северным и Балтийским морями, он предлагает уникальную морскую культуру с важными портовыми городами, такими как Киль и Любек. Регион известен своими парусными мероприятиями, музыкальным фестивалем Wacken Open Air и озерным краем Гольштейн.",
         de: "Schleswig-Holstein: Zwischen Nord- und Ostsee gelegen, bietet es eine einzigartige maritime Kultur, mit wichtigen Hafenstädten wie Kiel und Lübeck. Die Region ist bekannt für ihre Segelereignisse, das Wacken Open Air Musikfestival und die holsteinische Seenlandschaft.",
         el: "Σλέσβιχ-Χόλσταϊν: Βρίσκεται ανάμεσα στη Βόρεια Θάλασσα και τη Βαλτική Θάλασσα και προσφέρει μια μοναδική ναυτική κουλτούρα, με σημαντικές λιμενικές πόλεις όπως το Κίελο και η Λυβέκη. Η περιοχή είναι γνωστή για τις ιστιοπλοϊκές εκδηλώσεις, το μουσικό φεστιβάλ Wacken Open Air και την περιοχή λιμνών του Χόλσταϊν.",
         ro: "Schleswig-Holstein: Situat între Marea Nordului și Marea Baltică, oferă o cultură maritimă unică, cu orașe portuare importante precum Kiel și Lübeck. Regiunea este cunoscută pentru evenimentele sale de navigație, festivalul de muzică Wacken Open Air și zona lacurilor Holstein."
      },
      main_link:
         "https://www.schleswig-holstein.de/DE/landesregierung/ministerien-behoerden/LASD/Aufgaben/Gesundheitsberufe/AkademischeHeilberufe/Arzt/ArztHauptartikel.html",
      doctor_palat:
      "http://www.aeksh.de"
   },
   {
      id: 16,
      name: "Thüringen",
      key: "Thueringen",
      desc: {
         en: 'Thuringia: Known as the "green heart of Germany" with the Thuringian Forest and culturally significant cities such as Weimar, Erfurt, and Jena. Thuringia has a rich cultural history, associated with personalities like Goethe and Schiller, and is a center for optics and precision engineering.',
         fr: "Thuringe : Connu sous le nom de \"cœur vert de l'Allemagne\" avec la forêt de Thuringe et des villes culturellement importantes telles que Weimar, Erfurt et Jena. La Thuringe a une histoire culturelle riche, associée à des personnalités telles que Goethe et Schiller, et est un centre pour l'optique et la technique de précision.",
         es: 'Turingia: Conocida como el "corazón verde de Alemania" con el bosque de Turingia y ciudades culturalmente significativas como Weimar, Erfurt y Jena. Turingia tiene una rica historia cultural, asociada con personalidades como Goethe y Schiller, y es un centro de óptica y tecnología de precisión.',
         ar: 'تورينجيا: معروفة باسم "قلب ألمانيا الأخضر" مع غابة تورينجيا ومدن ثقافياً مهمة مثل فيمار وإرفورت وينا. تورينجيا لها تاريخ ثقافي غني، مرتبط بشخصيات مثل جوته وشيلر، وهي مركز للبصريات والهندسة الدقيقة.',
         tr: 'Thüringen: Thüringen Ormanı ve kültürel açıdan önemli şehirler olan Weimar, Erfurt ve Jena ile bilinen "Almanya\'nın yeşil kalbi" olarak bilinir. Thüringen, Goethe ve Schiller gibi kişiliklerle ilişkilendirilen zengin bir kültürel tarihe sahiptir ve optik ve hassas mühendislik için bir merkezdir.',
         pl: 'Turyngia: Znana jako "zielone serce Niemiec" z Lasem Turyńskim i kulturowo ważnymi miastami, takimi jak Weimar, Erfurt i Jena. Turyngia ma bogatą historię kulturalną, związaną z osobistościami takimi jak Goethe i Schiller, i jest centrum optyki i precyzyjnej techniki.',
         uk: 'Тюрингія: Відома як "зелене серце Німеччини" з Тюрингенським лісом та культурно важливими містами, такими як Веймар, Ерфурт і Єна. Тюрингія має багату культурну історію, пов\'язану з особистостями, такими як Гьоте та Шиллер, і є центром оптики та точної техніки.',
         ru: 'Тюрингия: Известная как "зеленое сердце Германии" с Тюрингенским лесом и культурно значимыми городами, такими как Веймар, Эрфурт и Йена. Тюрингия имеет богатую культурную историю, связанную с личностями, такими как Гёте и Шиллер, и является центром оптики и точной техники.',
         de: "Thüringen: Bekannt als das 'grüne Herz Deutschlands' mit dem Thüringer Wald und kulturell bedeutsamen Städten wie Weimar, Erfurt und Jena. Thüringen hat eine reiche kulturelle Geschichte, verbunden mit Persönlichkeiten wie Goethe und Schiller, und ist ein Zentrum für Optik und Präzisionstechnik.",
         el: "Θουριγγία: Γνωστή ως η «πράσινη καρδιά της Γερμανίας» με το Δάσος της Θουριγγίας και πολιτιστικά σημαντικές πόλεις όπως η Βαϊμάρη, η Έρφουρτ και η Γιένα. Η Θουριγγία διαθέτει πλούσια πολιτιστική ιστορία, συνδεδεμένη με προσωπικότητες όπως ο Γκαίτε και ο Σίλερ, και αποτελεί κέντρο οπτικής και ακριβείας μηχανικής.",
         ro: "Turingia: Cunoscută drept „inima verde a Germaniei” datorită Pădurii Turingiei și orașelor cu importanță culturală precum Weimar, Erfurt și Jena. Turingia are o istorie culturală bogată, asociată cu personalități ca Goethe și Schiller, și este un centru pentru optică și inginerie de precizie."
      },
      main_link:
         "https://landesverwaltungsamt.thueringen.de/soziales/gesundheitswesen/heilberufe/approbationen-und-berufserlaubnisse/approbation-fuer-auslaendische-studienabschluesse",
      doctor_palat:
      "http://www.laek-thueringen.de"
   },
   {
      id: 17,
      name: "Westfalen-Lippe",
      key: "WestfalenLippe",
      desc: {
         en: "Westphalian-Lippe is part of the federal state of Nordrhein-Westfalen, known for its vibrant industrial culture, modern art, and research-driven economy. This region, like the rest of Nordrhein-Westfalen, offers robust educational and professional opportunities for healthcare professionals. Both the Westphalian-Lippe Medical Chamber and the North Rhine Medical Chamber provide support and organize language and recognition exams for foreign doctors.",
         fr: "Westphalian-Lippe fait partie de l'État fédéral de Rhénanie-du-Nord-Westphalie, connu pour sa culture industrielle dynamique, son art moderne et son économie axée sur la recherche. Cette région, comme le reste de la Rhénanie-du-Nord-Westphalie, offre de solides opportunités éducatives et professionnelles pour les professionnels de santé. La chambre médicale de Westphalian-Lippe et celle de Rhénanie-du-Nord organisent des examens de langue et de reconnaissance pour les médecins étrangers.",
         es: "Westphalian-Lippe forma parte del estado federal de Renania del Norte-Westfalia, conocido por su vibrante cultura industrial, arte moderno y economía basada en la investigación. Esta región, al igual que el resto de Renania del Norte-Westfalia, ofrece sólidas oportunidades educativas y profesionales para los profesionales de la salud. Tanto la Cámara Médica de Westphalian-Lippe como la de Renania del Norte organizan exámenes de idioma y reconocimiento para médicos extranjeros.",
         ar: "وستفاليا-ليب هي جزء من ولاية شمال الراين - وستفاليا الفيدرالية، والمعروفة بثقافتها الصناعية الديناميكية، والفن الحديث، واقتصادها القائم على البحث. يوفر هذا الإقليم، مثل باقي شمال الراين - وستفاليا، فرصًا تعليمية ومهنية قوية للعاملين في المجال الطبي. تقدم غرفتا الطب في وستفاليا-ليب وشمال الراين الدعم وتنظم اختبارات اللغة والاعتراف للأطباء الأجانب.",
         tr: "Westfalen-Lippe, Almanya'nın Kuzey Ren-Vestfalya federal eyaletinin bir parçasıdır ve dinamik sanayi kültürü, modern sanat ve araştırma odaklı ekonomisiyle tanınır. Kuzey Ren-Vestfalya'nın geri kalanında olduğu gibi bu bölge, sağlık çalışanları için sağlam eğitim ve profesyonel fırsatlar sunar. Westfalen-Lippe Tıp Odası ve Kuzey Ren Tıp Odası, yabancı doktorlara destek sağlar ve dil ile tanıma sınavlarını düzenler.",
         pl: "Westfalia-Lippe jest częścią landu Nadrenia Północna-Westfalia, znanego z dynamicznej kultury przemysłowej, nowoczesnej sztuki i gospodarki opartej na badaniach. Region ten, podobnie jak reszta Nadrenii Północnej-Westfalii, oferuje solidne możliwości edukacyjne i zawodowe dla pracowników służby zdrowia. Izby lekarskie Westfalii-Lippe i Nadrenii Północnej organizują egzaminy językowe i uznaniowe dla zagranicznych lekarzy.",
         uk: "Вестфалія-Ліппе є частиною федеральної землі Північний Рейн-Вестфалія, відомої своєю динамічною промисловою культурою, сучасним мистецтвом і економікою, орієнтованою на дослідження. Як і решта Північного Рейну-Вестфалії, цей регіон пропонує потужні освітні та професійні можливості для медичних працівників. Медичні палати Вестфалії-Ліппе та Північного Рейну організовують мовні іспити та визнання для іноземних лікарів.",
         ru: "Вестфалия-Липпе является частью федеральной земли Северный Рейн-Вестфалия, известной своей динамичной промышленной культурой, современным искусством и экономикой, ориентированной на исследования. Как и остальные части Северного Рейна-Вестфалии, этот регион предлагает мощные образовательные и профессиональные возможности для медицинских работников. Медицинские палаты Вестфалии-Липпе и Северного Рейна организуют языковые экзамены и признание для иностранных врачей.",
         de: "Westfalen-Lippe ist Teil des Bundeslandes Nordrhein-Westfalen, das für seine lebendige Industriekultur, moderne Kunst und forschungsorientierte Wirtschaft bekannt ist. Wie der Rest Nordrhein-Westfalens bietet die Region hervorragende Bildungs- und Berufsmöglichkeiten für medizinisches Fachpersonal. Sowohl die Ärztekammer Westfalen-Lippe als auch die Ärztekammer Nordrhein organisieren Sprach- und Anerkennungsprüfungen für ausländische Ärzte.",
         el: "Η περιοχή Westfalen-Lippe αποτελεί τμήμα του ομόσπονδου κρατιδίου της Βόρειας Ρηνανίας-Βεστφαλίας, γνωστό για την έντονη βιομηχανική κουλτούρα, τη σύγχρονη τέχνη και την οικονομία που βασίζεται στην έρευνα. Όπως και στην υπόλοιπη Βόρεια Ρηνανία-Βεστφαλία, η περιοχή αυτή προσφέρει ισχυρές ευκαιρίες εκπαίδευσης και επαγγελματικής εξέλιξης για ιατρούς και άλλο ιατρικό προσωπικό. Τόσο ο Ιατρικός Σύλλογος Westfalen-Lippe όσο και ο Ιατρικός Σύλλογος Nordrhein παρέχουν υποστήριξη και διοργανώνουν γλωσσικές και αναγνωριστικές εξετάσεις για ξένους γιατρούς.",
         ro: "Westfalen-Lippe face parte din landul Renania de Nord-Westfalia, cunoscut pentru cultura sa industrială dinamică, arta modernă și o economie bazată pe cercetare. Ca și restul landului Renania de Nord-Westfalia, această regiune oferă oportunități puternice de educație și dezvoltare profesională pentru personalul medical. Atât Camera Medicală Westfalen-Lippe, cât și Camera Medicală North Rhine oferă sprijin și organizează examene de limbă și de recunoaștere pentru medicii străini."
      },
      main_link: "https://www.bezreg-muenster.de/de/gesundheit_und_soziales/zag/approbation_nrw/muenster/arzt/index.html",
      doctor_palat: "https://www.aekwl.de"
   },
];